import { fileURLToPath } from 'node:url'
import tailwindcss from '@tailwindcss/vite'
import react from '@vitejs/plugin-react'
import { defineConfig } from 'vite'

/**
 * Tailwind is a Vite plugin here, not a PostCSS plugin. That is the whole of
 * the v4 setup: no postcss.config.js, no tailwind.config.js, no `content`
 * globs. The theme lives in CSS (`src/design/tokens.css`) and the scanner finds
 * class names by walking the module graph, so there is nothing to keep in sync.
 */
export default defineConfig({
  plugins: [react(), tailwindcss()],

  resolve: {
    alias: {
      // Must agree with `paths` in tsconfig.json and with vitest.config.ts,
      // which merges this config rather than repeating it.
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },

  server: {
    port: 5173,
    /**
     * In development the app talks to MSW (src/test/browser.ts), not to a
     * server — see docs/specs/web/README.md §10. This proxy is what makes the
     * swap to the real API a configuration change: point it at the running
     * `services/api` and set VITE_USE_MOCKS=0. `request()` never carries an
     * origin, so nothing else in the app changes.
     */
    proxy: {
      '/api': {
        target: process.env.VITE_API_ORIGIN ?? 'http://localhost:3000',
        changeOrigin: true,
      },
    },
  },

  build: {
    target: 'es2022',
    /**
     * Sourcemaps in production because the alternative is triaging a minified
     * stack trace against a traceId, which is most of the value of §7 thrown
     * away to save a few hundred kilobytes nobody downloads.
     */
    sourcemap: true,
    /**
     * `public/` is **not** copied into the build. That is the opposite of Vite's
     * default (`copyPublicDir` is true), and it is deliberate.
     *
     * The directory holds exactly one file — `mockServiceWorker.js`, generated by
     * `msw init` — and it is dev-only. `src/test/browser.ts` argues at length that
     * MSW never reaches production, and it is correct about the *module*:
     * `main.tsx` reaches it through a dynamic `import()` behind
     * `import.meta.env.DEV`, which constant-folds to `false`, so Rollup drops the
     * branch and the chunk. Measured, not assumed — the production bundle contains
     * zero occurrences of `msw`, `setupWorker`, `onUnhandledRequest` or
     * `@flux/mocks`.
     *
     * The worker *script* is not in the module graph at all, so none of that
     * reasoning ever touched it. Vite copied it verbatim and
     * `dist/mockServiceWorker.js` shipped: a same-origin service worker sitting in
     * production, installable by anything that calls
     * `navigator.serviceWorker.register('/mockServiceWorker.js')`, after which it
     * intercepts every request from that origin and answers from a handler list —
     * persistently, across reloads, until something unregisters it. CodeQL's first
     * run on this repository flagged its `message` handler for acting on
     * postMessage data without checking the origin (`js/missing-origin-check`).
     * That handler is the smaller half of the problem; shipping the file at all is
     * the larger.
     *
     * This flag is blunt: a future `favicon.ico` dropped into `public/` would
     * silently not ship, which is a new silent failure in place of an old one. So
     * `scripts/check-public-assets.mjs` fails when `public/` holds anything but the
     * known dev-only artifacts, and says what to do instead. The failure mode is
     * converted, not accepted.
     */
    copyPublicDir: false,
    /**
     * The budget in docs/specs/web/README.md §8 is a first-paint number, so a
     * chunk that quietly grows past this is a budget failure and should be loud.
     *
     * It is currently exceeded, and recording that here is the point. This build
     * emits **one** chunk, ~611 kB minified and ~188 kB gzipped, because
     * `routes/router.tsx` deliberately has no `lazy` yet — see its "No `lazy` yet"
     * section, which defers the decision until the board needs a second pending
     * state inside the shell. So the warning fires on every build, by design.
     * Raising this limit to quiet it would delete the only standing signal that the
     * gap is still open.
     */
    chunkSizeWarningLimit: 250,
  },
})
