import { cva, type VariantProps } from 'class-variance-authority'
import { Avatar as AvatarPrimitive } from 'radix-ui'
import type * as React from 'react'
import { cn } from '@/lib/cn'

/**
 * Generated by `shadcn add avatar`, then retuned. README.md has the mapping.
 *
 * Three sizes, and they are the three that appear in the reference UI rather than
 * a t-shirt ladder for its own sake:
 *
 * | Size | Box | Initials | Where |
 * | --- | --- | --- | --- |
 * | `sm` | `size-avatar` — 24px | `text-xs` 11px | Board card, comment, list row, stacked group |
 * | `md` | `size-8` — 32px | `text-sm` 12px | Topbar account, assignee field, member row |
 * | `lg` | `size-10` — 40px | `text-md` 14px | Profile header, empty-state, mention card |
 *
 * `sm` is `size-avatar` and not `size-6` even though both are 24px, because
 * `--spacing-avatar` is what a row reserving space for one uses (`w-avatar`), and
 * a component whose size is spelled differently from the space allotted to it is
 * how the two drift apart.
 *
 * The fallback is `bg-surface-2 text-fg-muted` — **7.41:1** light, **6.97:1**
 * dark — and deliberately not a per-user colour, even though `tokens.css` now has
 * eight `--entity-*` pairs to pick from. This primitive does not know whose avatar
 * it is drawing. A team name, a project, a webhook and a person all render through
 * it, and only one of those has an identity worth hashing; a default hue here would
 * paint the other three at random. So the neutral pair is the base and
 * `<UserAvatar>` passes `className`, which `cn` merges over it.
 */
const avatarSizes = cva('relative flex shrink-0 overflow-hidden rounded-chip select-none', {
  variants: {
    size: {
      sm: 'size-avatar',
      md: 'size-8',
      lg: 'size-10',
    },
  },
  defaultVariants: { size: 'md' },
})

function Avatar({
  className,
  size = 'md',
  ...props
}: React.ComponentProps<typeof AvatarPrimitive.Root> & VariantProps<typeof avatarSizes>) {
  return (
    <AvatarPrimitive.Root
      data-slot="avatar"
      data-size={size}
      className={cn('group/avatar', avatarSizes({ size }), className)}
      {...props}
    />
  )
}

/**
 * `alt` is required, which is the one type change in this directory.
 *
 * Radix types it optional because `<img>` does. An avatar is never decorative —
 * it identifies a person, and the person's name is the alt text — so a missing
 * one is a real defect that `jsx-a11y/alt-text` cannot catch: the rule matches
 * `img`, and this renders as `AvatarPrimitive.Image`. Making it required moves the
 * check to `tsc`, which does run on it.
 *
 * `object-cover` is added. Without it a non-square upload is squashed to the
 * square by `aspect-square`, and profile photos are very often not square.
 */
function AvatarImage({
  className,
  alt,
  ...props
}: React.ComponentProps<typeof AvatarPrimitive.Image> & { alt: string }) {
  return (
    <AvatarPrimitive.Image
      data-slot="avatar-image"
      alt={alt}
      className={cn('aspect-square size-full object-cover', className)}
      {...props}
    />
  )
}

function AvatarFallback({
  className,
  ...props
}: React.ComponentProps<typeof AvatarPrimitive.Fallback>) {
  return (
    <AvatarPrimitive.Fallback
      data-slot="avatar-fallback"
      className={cn(
        'flex size-full items-center justify-center rounded-chip',
        'bg-surface-2 font-medium text-fg-muted',
        'group-data-[size=sm]/avatar:text-xs',
        'group-data-[size=md]/avatar:text-sm',
        'group-data-[size=lg]/avatar:text-md',
        className,
      )}
      {...props}
    />
  )
}

/**
 * The corner dot: presence, or a tiny status glyph.
 *
 * `ring-2 ring-surface` is a cut-out, not a focus ring — it separates the dot
 * from the photo underneath so it reads as sitting on top. It has to match the
 * surface behind the avatar, so on `canvas` a caller passes `ring-canvas`.
 *
 * A dot is never the only signal. Presence gets a `title`/`aria-label` on the
 * badge or, better, is stated in the tooltip that names the person — colour alone
 * cannot distinguish online from away, and `success-solid` next to `warning-solid`
 * at 8px is exactly the case a red/green-blind user cannot read.
 */
function AvatarBadge({ className, ...props }: React.ComponentProps<'span'>) {
  return (
    <span
      data-slot="avatar-badge"
      className={cn(
        'absolute right-0 bottom-0 z-10 inline-flex items-center justify-center',
        'rounded-chip bg-primary text-primary-fg ring-2 ring-surface select-none',
        'group-data-[size=sm]/avatar:size-2 group-data-[size=sm]/avatar:[&>svg]:hidden',
        'group-data-[size=md]/avatar:size-2.5 group-data-[size=md]/avatar:[&>svg]:size-2',
        'group-data-[size=lg]/avatar:size-3 group-data-[size=lg]/avatar:[&>svg]:size-2',
        className,
      )}
      {...props}
    />
  )
}

/**
 * Overlapped stack. `-space-x-2` is an 8px overlap on a 24px avatar — a third of
 * the width, which reads as a group without hiding the faces.
 *
 * The ring on each child is the same cut-out as `AvatarBadge`, and has the same
 * caveat: it must match the surface behind the stack.
 *
 * This is presentation only. A stack of five faces standing in for five names is
 * unreadable to a screen reader, so the *caller* labels the group — an
 * `aria-label` listing the people, or a visually hidden list beside it. That is
 * why there is no default `role` here: a wrong role is worse than none.
 */
function AvatarGroup({ className, ...props }: React.ComponentProps<'div'>) {
  return (
    <div
      data-slot="avatar-group"
      className={cn(
        'group/avatar-group flex -space-x-2',
        '*:data-[slot=avatar]:ring-2 *:data-[slot=avatar]:ring-surface',
        className,
      )}
      {...props}
    />
  )
}

/**
 * The `+3` at the end of a stack. Sizes itself from the avatars beside it via
 * `group-has-*`, so a caller cannot set the group to `sm` and leave the counter at
 * 32px — the two cannot disagree because only one of them is configured.
 */
function AvatarGroupCount({ className, ...props }: React.ComponentProps<'div'>) {
  return (
    <div
      data-slot="avatar-group-count"
      className={cn(
        'relative flex size-8 shrink-0 items-center justify-center rounded-chip',
        'bg-surface-2 text-sm font-medium text-fg-muted ring-2 ring-surface',
        'group-has-data-[size=sm]/avatar-group:size-avatar',
        'group-has-data-[size=sm]/avatar-group:text-xs',
        'group-has-data-[size=lg]/avatar-group:size-10',
        'group-has-data-[size=lg]/avatar-group:text-md',
        '[&>svg]:size-4',
        'group-has-data-[size=sm]/avatar-group:[&>svg]:size-3',
        'group-has-data-[size=lg]/avatar-group:[&>svg]:size-5',
        className,
      )}
      {...props}
    />
  )
}

export { Avatar, AvatarBadge, AvatarFallback, AvatarGroup, AvatarGroupCount, AvatarImage }
