import { cva, type VariantProps } from 'class-variance-authority'
import { Slot } from 'radix-ui'
import type * as React from 'react'
import { cn } from '@/lib/cn'

/**
 * Generated by `shadcn add badge`, then retuned. README.md has the mapping.
 *
 * The variant set is the biggest change. The generator produced
 * `default | secondary | destructive | outline | ghost | link` — an action
 * vocabulary borrowed from Button. A badge is not an action; it is a *reading* of
 * something, and the reading this product has to render is the contract's:
 * `StatusCategorySchema`, `PrioritySchema` and `slaState`. So the variants are
 * tones, and every one of them is a measured `*-soft` / `*-soft-fg` pair rather
 * than an alpha blend, so a chip on `canvas` and the same chip on `surface` are
 * the same colour.
 *
 * All six tone pairs clear 4.5:1 on their own fill — they are text, not
 * decoration. Ratios are in `tokens.css` beside each token.
 *
 * A tone is never the only carrier of meaning: every badge has a label, and the
 * board's status chips add a shape as well. `docs/specs/web/README.md` §9 is
 * explicit about this and red/green is the case it has in mind.
 */
const badgeVariants = cva(
  [
    'inline-flex w-fit shrink-0 items-center justify-center gap-1 overflow-hidden',
    'rounded-chip border border-transparent whitespace-nowrap',
    'transition-colors duration-90 ease-out',
    "[&>svg]:pointer-events-none [&>svg]:shrink-0 [&>svg:not([class*='size-'])]:size-3.5",
  ],
  {
    variants: {
      variant: {
        /** No opinion. Labels, counts, a component name. */
        neutral: 'bg-neutral-soft text-neutral-soft-fg',
        /** Belongs to the brand: an active filter, the current sprint. */
        primary: 'bg-primary-soft text-primary-soft-fg',
        /** `done`, resolved, merged, `slaState: ok`. */
        success: 'bg-success-soft text-success-soft-fg',
        /** `slaState: at_risk`, a due date inside the window, a soft limit hit. */
        warning: 'bg-warning-soft text-warning-soft-fg',
        /** `in_progress`, informational counts. */
        info: 'bg-info-soft text-info-soft-fg',
        /** `slaState: breached`, `blocker` priority, a failed import. */
        danger: 'bg-danger-soft text-danger-soft-fg',
        /**
         * The reference's category chip: outlined, no fill, so a row of them
         * beside a filled status chip does not compete with it.
         */
        outline: 'border-border-strong text-fg-muted',
      },
      size: {
        /**
         * The uppercase micro-label. `text-label` carries 600 weight and 0.08em
         * tracking in the token itself, which is what stops uppercase text from
         * setting as a solid block.
         */
        sm: 'h-6 px-2 text-label uppercase',
        /**
         * The board card's label pill, measured off `UI Images/JIRA 1` and
         * `JIRA 2`: 24px tall, 8px of horizontal padding, 15px semibold, sentence
         * case, **no tracking**.
         *
         * It is `sm`'s box with `sm`'s typography removed, and the arithmetic is
         * what separates them. The reference's two pills measure 73px and 65px of
         * fill for "Website" and "Design" — 7 and 6 characters. 15px semibold sets
         * those at 57px and 49px, so 73 − 57 = 16 = two 8px paddings, and the same
         * subtraction gives 16 for the second pill. `text-label`'s 0.08em would add
         * 1.2px per character, which is 8px on "Website" alone and puts the pill at
         * 81px — visibly wider than the reference at the size that repeats most
         * often on the screen.
         *
         * So this rung exists rather than `LabelChip` overriding two of `sm`'s
         * classes: a variant that has to be half-undone at its only call site is a
         * variant that was the wrong shape.
         */
        chip: 'h-6 px-2 text-sm font-semibold',
        /**
         * Both heights moved up with the measured type scale — 18/20 became 24/28.
         * `text-xs` is 14px on a 20px line-height, and a 20px line in a 20px box has
         * nowhere for a descender to go, so `h-5` was not a smaller chip: it was a
         * clipped one. 28px is also `Button`'s `xs` rung, which is what lets a chip
         * and a row action sit on one line without either being nudged.
         */
        md: 'h-7 px-2.5 text-xs font-medium',
      },
    },
    defaultVariants: {
      variant: 'neutral',
      size: 'md',
    },
  },
)

function Badge({
  className,
  variant = 'neutral',
  size = 'md',
  asChild = false,
  ...props
}: React.ComponentProps<'span'> & VariantProps<typeof badgeVariants> & { asChild?: boolean }) {
  const Comp = asChild ? Slot.Root : 'span'

  return (
    <Comp
      data-slot="badge"
      data-variant={variant}
      data-size={size}
      className={cn(badgeVariants({ variant, size }), className)}
      {...props}
    />
  )
}

export { Badge, badgeVariants }
