import { cva, type VariantProps } from 'class-variance-authority'
import { Slot } from 'radix-ui'
import type * as React from 'react'
import { cn } from '@/lib/cn'

/**
 * Generated by `shadcn add button`, then retuned. See README.md in this
 * directory for the full mapping; the notes here are what is specific to this
 * component.
 *
 * Height ladder is 24 / 28 / 32 / 40px against the generator's 32 / 36 / 40 —
 * measured off `UI Images/`, where a toolbar button is 28px and the primary CTA
 * is 32px. The whole ladder is shared with Input and SelectTrigger so a filter
 * row lines up without per-component nudging.
 *
 * `hover:bg-primary-hover`, not `hover:bg-primary/90`. An opacity-based hover
 * blends with whatever is behind the button, so the same button hovers to two
 * different colours on `canvas` and on `surface`. `--primary-hover` is a
 * measured second colour (`#5f3dff`, white on it 5.8:1).
 *
 * No focus ring: `tokens.css` draws one outline for the whole product. README §4
 * is why, and it is not a shortcut.
 *
 * `disabled:opacity-50` is kept from the generated code. WCAG 2.2 exempts
 * inactive controls from 1.4.3, so the reduced contrast is allowed — and 50% is
 * unambiguous, which matters more than looking good on a button nobody can press.
 */
const buttonVariants = cva(
  [
    'inline-flex shrink-0 items-center justify-center gap-1.5 whitespace-nowrap',
    'rounded-control font-medium transition-colors duration-90 ease-out',
    'disabled:pointer-events-none disabled:opacity-50',
    // Icons never intercept the click, never shrink under a long label, and take
    // the size their row wants unless the caller has said otherwise.
    "[&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4",
  ],
  {
    variants: {
      variant: {
        /** The brand action. One per view, at most. */
        primary: 'bg-primary text-primary-fg shadow-xs hover:bg-primary-hover',
        /**
         * The near-black CTA from the reference video's `＋ Create task`.
         * `--contrast` inverts with the theme, so this is near-white on dark
         * rather than a black button nobody can read.
         */
        contrast: 'bg-contrast text-contrast-fg shadow-xs hover:bg-contrast-hover',
        /**
         * The workhorse. `border-control` rather than `border` because this
         * border *is* the control's boundary — 4.03:1 light, 3.99:1 dark on the
         * `surface` it fills with, which is what SC 1.4.11 asks for and what
         * decorative `border` (1.3:1) does not meet.
         */
        secondary:
          'border border-border-control bg-surface text-fg shadow-xs hover:bg-surface-2 focus-visible:border-ring',
        /** Toolbar and row actions. Quiet until hovered, then a surface step. */
        ghost: 'text-fg-muted hover:bg-surface-3 hover:text-fg',
        /**
         * Irreversible. `danger-solid` carries `danger-fg` at 4.80:1 — AA with
         * 0.30 to spare, and the number is re-derived from `tokens.css` on every
         * run by `design/contrast.test.ts`. This comment claimed 4.9:1 until that
         * test existed to contradict it.
         */
        danger: 'bg-danger-solid text-danger-fg shadow-xs hover:bg-danger-hover',
        /**
         * Destructive but not the point of the screen — "Remove" in a settings
         * row. `danger-accent` is the text-weight red (5.9:1 on white), not the
         * fill-weight one.
         */
        'danger-ghost': 'text-danger-accent hover:bg-danger-soft hover:text-danger-soft-fg',
        /** Inline in prose. Underline on hover only, offset clear of descenders. */
        link: 'text-primary underline-offset-4 hover:underline',
      },
      size: {
        xs: "h-6 gap-1 px-2 text-xs [&_svg:not([class*='size-'])]:size-3.5",
        sm: "h-7 px-2.5 text-sm [&_svg:not([class*='size-'])]:size-3.5",
        md: 'h-8 px-3 text-base',
        lg: "h-10 gap-2 px-4 text-md [&_svg:not([class*='size-'])]:size-4.5",
        /** Square, for a button whose whole content is one icon. */
        'icon-xs': "size-6 [&_svg:not([class*='size-'])]:size-3.5",
        'icon-sm': "size-7 [&_svg:not([class*='size-'])]:size-3.5",
        icon: 'size-8',
        'icon-lg': "size-10 [&_svg:not([class*='size-'])]:size-4.5",
      },
    },
    defaultVariants: {
      variant: 'secondary',
      size: 'md',
    },
  },
)

/**
 * `variant` defaults to `secondary`, not `primary`.
 *
 * Deliberate: a `<Button>` with no props should be the safe, repeatable one. A
 * screen full of accidental brand-violet buttons has no hierarchy left to spend,
 * and `primary` is one word away when it is genuinely the main action.
 */
function Button({
  className,
  variant = 'secondary',
  size = 'md',
  asChild = false,
  ...props
}: React.ComponentProps<'button'> & VariantProps<typeof buttonVariants> & { asChild?: boolean }) {
  const Comp = asChild ? Slot.Root : 'button'

  return (
    <Comp
      data-slot="button"
      data-variant={variant}
      data-size={size}
      className={cn(buttonVariants({ variant, size }), className)}
      {...props}
    />
  )
}

export { Button, buttonVariants }
