import { Check, Minus } from 'lucide-react'
import { Checkbox as CheckboxPrimitive } from 'radix-ui'
import type * as React from 'react'
import { cn } from '@/lib/cn'

/**
 * Generated by `shadcn add checkbox`, then retuned. README.md has the mapping.
 *
 * Two changes here are functional rather than cosmetic.
 *
 * **Indeterminate.** The generated component renders one icon and ignores
 * `checked="indeterminate"`, which Radix supports and this product needs: the
 * select-all box in a list header is indeterminate whenever some but not all
 * rows are selected, and `POST /issues/bulk` exists precisely so that selection
 * can be acted on. Without the third state that header box has to lie — showing
 * either checked or unchecked for a partial selection — and a user who clicks it
 * gets an outcome they did not predict. Radix mounts the Indicator for `checked`
 * *and* `indeterminate`, so both icons live inside it and the named group picks
 * one.
 *
 * **`outline-none` is gone.** The generated class set opens with
 * `outline-none focus-visible:ring-[3px]`, and dropping only the ring would have
 * left a control with no focus indicator at all: Tailwind utilities sit in a
 * later cascade layer than `@layer base`, so `outline-none` beats the global
 * `:focus-visible` rule regardless of specificity. Nothing in this directory may
 * carry `outline-none` or `outline-hidden` (README §4).
 *
 * **Geometry.** 16px box, 1px border, so a 14px interior; a lucide glyph inks
 * about 11.7px of its 14px box, which leaves ~1px of fill visible around the
 * check rather than a mark jammed into the corners. `rounded-sm` (4px) is the one
 * place Tailwind's own radius scale is used instead of ours — at 16px, our 8px
 * `rounded-control` reads as a circle, and a circle means radio.
 *
 * The `before:` pseudo-element is hit area, not appearance. WCAG 2.2 SC 2.5.8
 * asks for 24x24 and the visual box is 16; `-inset-1` adds 4px on every side.
 * A pseudo-element belongs to its host's hit area, so this costs no wrapper and
 * moves nothing.
 */
function Checkbox({ className, ...props }: React.ComponentProps<typeof CheckboxPrimitive.Root>) {
  return (
    <CheckboxPrimitive.Root
      data-slot="checkbox"
      className={cn(
        'group/checkbox peer relative size-4 shrink-0 rounded-sm',
        'border border-border-control bg-surface shadow-xs',
        'transition-colors duration-90 ease-out',
        'before:absolute before:-inset-1',
        'data-[state=checked]:border-primary data-[state=checked]:bg-primary',
        'data-[state=checked]:text-primary-fg',
        'data-[state=indeterminate]:border-primary data-[state=indeterminate]:bg-primary',
        'data-[state=indeterminate]:text-primary-fg',
        'aria-invalid:border-danger-accent',
        'disabled:cursor-not-allowed disabled:opacity-50',
        className,
      )}
      {...props}
    >
      <CheckboxPrimitive.Indicator
        data-slot="checkbox-indicator"
        className="grid place-content-center text-current"
      >
        <Check
          aria-hidden="true"
          strokeWidth={3}
          className="hidden size-3.5 group-data-[state=checked]/checkbox:block"
        />
        <Minus
          aria-hidden="true"
          strokeWidth={3}
          className="hidden size-3.5 group-data-[state=indeterminate]/checkbox:block"
        />
      </CheckboxPrimitive.Indicator>
    </CheckboxPrimitive.Root>
  )
}

export { Checkbox }
