import { X } from 'lucide-react'
import { Dialog as DialogPrimitive } from 'radix-ui'
import { useRef } from 'react'
import type * as React from 'react'
import { Button } from '@/components/ui/button'
import { cn } from '@/lib/cn'

/**
 * Generated by `shadcn add dialog`, then retuned. README.md has the mapping.
 *
 * **Use it sparingly.** "Modal overload" is one of the Jira failure modes the
 * product bar names explicitly, and a dialog is the most interruptive surface
 * there is: it takes focus, traps it, blocks the page behind it, and cannot be
 * linked to or left open while the user checks something else. Creating an issue,
 * editing a field, moving a card and filtering a board are all better as inline
 * editing, a popover, or a route. What a dialog is genuinely for: a destructive
 * confirmation, and a short focused task that must complete or abort.
 *
 * Changes worth knowing about:
 *
 * - `bg-overlay` replaces `bg-black/50`. A 50%-black scrim over a dark theme is
 *   nearly invisible; `--overlay` is measured per theme (0.42 alpha light, 0.62
 *   dark).
 * - `w-[calc(100%-2rem)] max-w-lg` replaces `max-w-[calc(100%-2rem)] sm:max-w-lg`
 *   — one declaration instead of a breakpoint. Below 544px the width binds and
 *   leaves a 16px gutter; above it, `max-w-lg` (512px) binds. Same result, no
 *   media query, nothing to keep in step.
 * - `max-h-[calc(100dvh-4rem)] overflow-y-auto` is new. A dialog containing a form
 *   longer than the viewport previously ran off the top and bottom of the screen
 *   with no way to reach either end. `dvh` rather than `vh` because mobile browser
 *   chrome makes `vh` taller than what is actually visible. The 20px of padding
 *   keeps focus outlines clear of the scroll boundary.
 * - `top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2` replaces four arbitrary
 *   percentage values that meant the same thing.
 * - `duration-200` is gone; the enter/exit animations carry their own timing, and
 *   200ms was not one of the values in `design/motion.ts`.
 * - **`outline-none` is gone.** Radix moves focus to the content when the dialog
 *   opens, so that class removed the indicator from the element being focused.
 *   Removing it does *not* mean a mouse user sees an outline around the whole
 *   dialog: the rule is `:focus-visible`, and a browser does not match it for
 *   programmatic focus on a non-text element unless the user was already
 *   navigating by keyboard — which is exactly when they need it.
 * - The close button is a real `Button` (`ghost`, `icon-sm`) instead of a
 *   hand-rolled one with `ring-offset-background` and `focus:outline-hidden`. One
 *   less thing that hovers and focuses differently from every other icon button.
 */
function Dialog({ ...props }: React.ComponentProps<typeof DialogPrimitive.Root>) {
  return <DialogPrimitive.Root data-slot="dialog" {...props} />
}

function DialogTrigger({ ...props }: React.ComponentProps<typeof DialogPrimitive.Trigger>) {
  return <DialogPrimitive.Trigger data-slot="dialog-trigger" {...props} />
}

function DialogPortal({ ...props }: React.ComponentProps<typeof DialogPrimitive.Portal>) {
  return <DialogPrimitive.Portal data-slot="dialog-portal" {...props} />
}

function DialogClose({ ...props }: React.ComponentProps<typeof DialogPrimitive.Close>) {
  return <DialogPrimitive.Close data-slot="dialog-close" {...props} />
}

function DialogOverlay({
  className,
  ...props
}: React.ComponentProps<typeof DialogPrimitive.Overlay>) {
  return (
    <DialogPrimitive.Overlay
      data-slot="dialog-overlay"
      className={cn(
        'fixed inset-0 z-50 bg-overlay',
        'data-[state=closed]:animate-fade-out data-[state=open]:animate-fade-in',
        className,
      )}
      {...props}
    />
  )
}

/**
 * ### Focus goes back where it came from
 *
 * Radix's modal `DialogContent` restores focus to `DialogTrigger`, and to nothing
 * at all when there is no trigger:
 *
 * ```js
 * // @radix-ui/react-dialog@1.1.23/dist/index.mjs:154
 * onCloseAutoFocus: composeEventHandlers(props.onCloseAutoFocus, (event) => {
 *   event.preventDefault()
 *   context.triggerRef.current?.focus()   // null for a controlled dialog
 * })
 * ```
 *
 * Every dialog in flux is controlled — `ConfirmDialog` takes `open` and
 * `onOpenChange`, because the thing that opens it is as often a dropdown item or a
 * row action as a button sitting next to it. `triggerRef` is therefore `null`, the
 * `preventDefault()` above cancels `FocusScope`'s own correct restore, and closing
 * the dialog leaves `document.activeElement` on `<body>`. Measured, not inferred:
 * that is what put focus on the body in `data/confirm-dialog.test.tsx`.
 *
 * For a keyboard or screen-reader user that is not a cosmetic bug. Tab resumes from
 * the top of the document, so dismissing a confirmation costs them their place in
 * the page — WCAG 2.2 2.4.3, and the reason `docs/product-quality-bar.md` lists
 * keyboard as a state every feature is verified in.
 *
 * So the opener is captured and restored here instead:
 *
 * - **`onOpenAutoFocus` is the capture point**, because it is the last moment the
 *   opener still has focus. `FocusScope` reads `document.activeElement`, dispatches
 *   this event, and only then moves focus into the dialog
 *   (`@radix-ui/react-focus-scope/dist/index.mjs:79-87`). Reading it from an effect
 *   in this component would be too late — child effects run first, so focus is
 *   already on the first tabbable control inside.
 * - **`preventDefault()` on close suppresses the Radix handler**, since both the
 *   modal and non-modal paths check `defaultPrevented` before touching
 *   `triggerRef`. When a `DialogTrigger` *is* used it makes no difference: the
 *   trigger is what had focus, so it is what was captured.
 * - **A detached opener is left alone.** Deleting the row that owns the ⋯ menu is
 *   the ordinary case for a destructive confirmation, and focusing a node that is
 *   no longer in the document does nothing at all. Falling through gives Radix's
 *   trigger-based restore its chance; a surface that knows where focus should land
 *   after a delete passes its own `onCloseAutoFocus` and calls `preventDefault()`.
 *
 * `onOpenAutoFocus` capture happens before the caller's handler and `onCloseAutoFocus`
 * restore after it, so a caller that wants to place focus itself wins both ways.
 */
function DialogContent({
  className,
  children,
  showCloseButton = true,
  onOpenAutoFocus,
  onCloseAutoFocus,
  ...props
}: React.ComponentProps<typeof DialogPrimitive.Content> & {
  showCloseButton?: boolean | undefined
}) {
  const openerRef = useRef<HTMLElement | null>(null)

  return (
    <DialogPortal>
      <DialogOverlay />
      <DialogPrimitive.Content
        data-slot="dialog-content"
        onOpenAutoFocus={(event) => {
          const active = document.activeElement
          openerRef.current = active instanceof HTMLElement ? active : null
          onOpenAutoFocus?.(event)
        }}
        onCloseAutoFocus={(event) => {
          onCloseAutoFocus?.(event)
          const opener = openerRef.current
          openerRef.current = null
          if (event.defaultPrevented || opener === null || !opener.isConnected) return
          event.preventDefault()
          opener.focus({ preventScroll: true })
        }}
        className={cn(
          'fixed top-1/2 left-1/2 z-50 -translate-x-1/2 -translate-y-1/2',
          'grid w-[calc(100%-2rem)] max-w-lg gap-4',
          'max-h-[calc(100dvh-4rem)] overflow-y-auto',
          'rounded-panel border border-border bg-surface p-5 shadow-overlay',
          'data-[state=closed]:animate-pop-out data-[state=open]:animate-pop-in',
          className,
        )}
        {...props}
      >
        {children}
        {showCloseButton && (
          <DialogPrimitive.Close asChild>
            <Button variant="ghost" size="icon-sm" className="absolute top-4 right-4">
              <X />
              <span className="sr-only">Close</span>
            </Button>
          </DialogPrimitive.Close>
        )}
      </DialogPrimitive.Content>
    </DialogPortal>
  )
}

/**
 * Left-aligned in every size. The generated `text-center sm:text-left` centred the
 * title on narrow screens, which is a native-alert idiom — flux dialogs are
 * focused tasks with forms in them, and a heading that moves depending on window
 * width is the kind of small unpredictability the product bar rules out.
 */
function DialogHeader({ className, ...props }: React.ComponentProps<'div'>) {
  return (
    <div data-slot="dialog-header" className={cn('flex flex-col gap-1', className)} {...props} />
  )
}

/**
 * `flex-col-reverse` below `sm` is deliberate and is kept from the generated
 * version: stacked vertically, the primary action should be the top button — it is
 * both the first thing read and the one nearest the thumb — while in a row it
 * belongs on the right. Reversing the column is how one DOM order, with the
 * primary action last, gets both.
 */
function DialogFooter({
  className,
  showCloseButton = false,
  children,
  ...props
}: React.ComponentProps<'div'> & {
  showCloseButton?: boolean | undefined
}) {
  return (
    <div
      data-slot="dialog-footer"
      className={cn('flex flex-col-reverse gap-2 pt-1 sm:flex-row sm:justify-end', className)}
      {...props}
    >
      {children}
      {showCloseButton && (
        <DialogPrimitive.Close asChild>
          <Button variant="secondary">Close</Button>
        </DialogPrimitive.Close>
      )}
    </div>
  )
}

/**
 * `pr-8` reserves the corner the close button occupies, so a long title wraps
 * before it collides rather than running underneath it. It costs 32px of right
 * margin when there is no close button, which is invisible on left-aligned text.
 *
 * `leading-none` is dropped. At 16px it clips descenders as soon as the title
 * wraps to a second line; the `--text-lg` token already carries a 24px line height.
 */
function DialogTitle({ className, ...props }: React.ComponentProps<typeof DialogPrimitive.Title>) {
  return (
    <DialogPrimitive.Title
      data-slot="dialog-title"
      className={cn('pr-8 text-lg font-semibold text-fg', className)}
      {...props}
    />
  )
}

function DialogDescription({
  className,
  ...props
}: React.ComponentProps<typeof DialogPrimitive.Description>) {
  return (
    <DialogPrimitive.Description
      data-slot="dialog-description"
      className={cn('text-sm text-fg-muted', className)}
      {...props}
    />
  )
}

export {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogOverlay,
  DialogPortal,
  DialogTitle,
  DialogTrigger,
}
