import { Check, ChevronRight } from 'lucide-react'
import { DropdownMenu as DropdownMenuPrimitive } from 'radix-ui'
import type * as React from 'react'
import { cn } from '@/lib/cn'

/**
 * Generated by `shadcn add dropdown-menu`, then retuned. README.md has the mapping.
 *
 * This is the row-action and overflow menu: the `⋯` on an issue card, the avatar
 * menu, the `+` in a board column header. It is a *menu* in the ARIA sense —
 * `role="menu"`, arrow-key navigation, one item invoked per open — so it holds
 * commands, not content and not a form. A menu item that opens a dialog is fine; a
 * menu item containing an input is a popover wearing the wrong component.
 *
 * ### Item geometry, since it has to line up with everything else
 *
 * `text-base` is 13px on a 20px line box, and `py-1.5` adds 6px above and below:
 * **32px per item**, which is `--spacing-row` and the height of a `default`
 * button, a `default` select trigger and a table row. A menu opened from a 32px
 * toolbar button therefore has rows the same height as the button that opened it,
 * which is the sort of thing nobody notices working and everybody notices broken.
 *
 * With `p-1` (4px) on the content, a five-item menu is 4 + 5×32 + 4 = 168px tall.
 *
 * ### Divergences from the generated file
 *
 * - **`variant="danger"`, not `variant="destructive"`.** `Button` already spells
 *   this family `danger` / `danger-ghost`, and the tokens are `--danger-*`. Two
 *   names for one concept is how a codebase ends up with both spellings in the
 *   same file six months later. The `data-variant` attribute changed with it.
 * - **The `!` important on the destructive icon colour is gone.** It existed to
 *   beat the generated `[&_svg:not([class*='text-'])]:text-muted-foreground` in the
 *   same string. `[&_svg]:text-current` under the same variant does it without
 *   importance, because the icon inherits from an item whose text colour is
 *   already correct.
 * - **`checked` is no longer destructured and re-passed.** `checked={checked}`
 *   after pulling it out of the props was a no-op that also failed to compile:
 *   under this repo's `exactOptionalPropertyTypes: true`, writing an explicit
 *   `checked` prop whose value may be `undefined` is not assignable to an
 *   `optional` prop, while letting it flow through the spread is. The generated
 *   code had a real type error, not a nuisance one — passing `checked={undefined}`
 *   explicitly makes Radix treat the item as uncontrolled.
 * - **The radio dot is a `span`, not `<CircleIcon className="fill-current" />`.**
 *   Same call as in `radio-group.tsx`: a 6px circle is `size-1.5 rounded-chip`,
 *   and an SVG whose only job is to be round costs a component, an import and a
 *   `fill` override.
 * - **Labels are `text-xs text-fg-muted`, not `text-sm`.** A section label at the
 *   same size and weight as the commands under it competes with them; this matches
 *   `SelectLabel` so the two menus read as one family.
 * - `outline-hidden` is gone from all five focusable parts, `dark:` colour variants
 *   are gone, and `focus-visible:-outline-offset-2` draws the focus ring *inside*
 *   each item because the content is an `overflow-y-auto` box that would otherwise
 *   clip the ring on the first and last rows.
 */
function DropdownMenu({ ...props }: React.ComponentProps<typeof DropdownMenuPrimitive.Root>) {
  return <DropdownMenuPrimitive.Root data-slot="dropdown-menu" {...props} />
}

function DropdownMenuPortal({
  ...props
}: React.ComponentProps<typeof DropdownMenuPrimitive.Portal>) {
  return <DropdownMenuPrimitive.Portal data-slot="dropdown-menu-portal" {...props} />
}

function DropdownMenuTrigger({
  ...props
}: React.ComponentProps<typeof DropdownMenuPrimitive.Trigger>) {
  return <DropdownMenuPrimitive.Trigger data-slot="dropdown-menu-trigger" {...props} />
}

/**
 * `min-w-40` (160px) rather than the generated 8rem. An action menu carries verbs
 * and often a shortcut hint on the right — "Move to sprint" plus `⌘⇧M` does not
 * fit in 128px, and a menu that sizes itself to its longest item looks arbitrary
 * next to one that does not.
 */
function DropdownMenuContent({
  className,
  sideOffset = 4,
  ...props
}: React.ComponentProps<typeof DropdownMenuPrimitive.Content>) {
  return (
    <DropdownMenuPrimitive.Portal>
      <DropdownMenuPrimitive.Content
        data-slot="dropdown-menu-content"
        sideOffset={sideOffset}
        className={cn(
          'z-40 min-w-40 max-h-(--radix-dropdown-menu-content-available-height)',
          'origin-(--radix-dropdown-menu-content-transform-origin)',
          'overflow-x-hidden overflow-y-auto',
          'rounded-card border border-border bg-surface p-1 text-fg shadow-overlay',
          'data-[state=open]:animate-pop-in data-[state=closed]:animate-pop-out',
          'data-[side=bottom]:pop-from-top data-[side=top]:pop-from-bottom',
          'data-[side=left]:pop-from-right data-[side=right]:pop-from-left',
          className,
        )}
        {...props}
      />
    </DropdownMenuPrimitive.Portal>
  )
}

function DropdownMenuGroup({ ...props }: React.ComponentProps<typeof DropdownMenuPrimitive.Group>) {
  return <DropdownMenuPrimitive.Group data-slot="dropdown-menu-group" {...props} />
}

/**
 * The shared shape of every row in this menu — item, checkbox item, radio item and
 * sub-trigger. It is a plain string rather than a `cva` because there are no
 * variants on it; the two that do vary (`danger`, `inset`) are `data-` attributes,
 * which keeps them settable from the DOM and inspectable in devtools.
 */
const menuItemBase = [
  'relative flex cursor-default items-center gap-2 select-none',
  'rounded-control px-2 py-1.5 text-base',
  'focus:bg-surface-3 focus-visible:-outline-offset-2',
  'data-[inset]:pl-8',
  'data-[disabled]:pointer-events-none data-[disabled]:opacity-50',
  "[&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-3.5",
  "[&_svg:not([class*='text-'])]:text-fg-muted",
].join(' ')

/**
 * `danger` is for an action that destroys or detaches something — Delete issue,
 * Remove from sprint, Revoke access. It is *not* for anything merely consequential:
 * an entire menu of red items communicates nothing, and it trains people to click
 * past the colour. One per menu, last in the list, behind a separator.
 *
 * `text-danger-accent` measures 5.74:1 light / 7.11:1 dark on the menu surface and
 * 5.15:1 / 5.69:1 on the `surface-3` focus fill, so the item stays legible in the
 * state where it is about to be pressed. On focus it also swaps to
 * `bg-danger-soft` / `text-danger-soft-fg` (6.47:1 / 9.77:1) — a red row under the
 * cursor is a clearer warning than red text on grey.
 */
function DropdownMenuItem({
  className,
  inset,
  variant = 'default',
  ...props
}: React.ComponentProps<typeof DropdownMenuPrimitive.Item> & {
  inset?: boolean | undefined
  variant?: 'default' | 'danger' | undefined
}) {
  return (
    <DropdownMenuPrimitive.Item
      data-slot="dropdown-menu-item"
      data-inset={inset}
      data-variant={variant}
      className={cn(
        menuItemBase,
        'data-[variant=danger]:text-danger-accent',
        'data-[variant=danger]:focus:bg-danger-soft',
        'data-[variant=danger]:focus:text-danger-soft-fg',
        'data-[variant=danger]:[&_svg]:text-current',
        className,
      )}
      {...props}
    />
  )
}

/**
 * The 32px gutter is `pl-8`, and the indicator sits at `left-2` in a `size-3.5`
 * box — so the check is centred on x = 8 + 7 = 15px, which is where the radio dot
 * and the `data-inset` text edge also land. All three agree because they are all
 * derived from the same two numbers rather than eyeballed separately.
 */
function DropdownMenuCheckboxItem({
  className,
  children,
  ...props
}: React.ComponentProps<typeof DropdownMenuPrimitive.CheckboxItem>) {
  return (
    <DropdownMenuPrimitive.CheckboxItem
      data-slot="dropdown-menu-checkbox-item"
      className={cn(menuItemBase, 'pr-2 pl-8', className)}
      {...props}
    >
      <span className="pointer-events-none absolute left-2 flex size-3.5 items-center justify-center">
        <DropdownMenuPrimitive.ItemIndicator>
          <Check aria-hidden="true" className="text-primary-accent" />
        </DropdownMenuPrimitive.ItemIndicator>
      </span>
      {children}
    </DropdownMenuPrimitive.CheckboxItem>
  )
}

function DropdownMenuRadioGroup({
  ...props
}: React.ComponentProps<typeof DropdownMenuPrimitive.RadioGroup>) {
  return <DropdownMenuPrimitive.RadioGroup data-slot="dropdown-menu-radio-group" {...props} />
}

function DropdownMenuRadioItem({
  className,
  children,
  ...props
}: React.ComponentProps<typeof DropdownMenuPrimitive.RadioItem>) {
  return (
    <DropdownMenuPrimitive.RadioItem
      data-slot="dropdown-menu-radio-item"
      className={cn(menuItemBase, 'pr-2 pl-8', className)}
      {...props}
    >
      <span className="pointer-events-none absolute left-2 flex size-3.5 items-center justify-center">
        <DropdownMenuPrimitive.ItemIndicator>
          <span className="size-1.5 rounded-chip bg-primary-accent" />
        </DropdownMenuPrimitive.ItemIndicator>
      </span>
      {children}
    </DropdownMenuPrimitive.RadioItem>
  )
}

function DropdownMenuLabel({
  className,
  inset,
  ...props
}: React.ComponentProps<typeof DropdownMenuPrimitive.Label> & {
  inset?: boolean | undefined
}) {
  return (
    <DropdownMenuPrimitive.Label
      data-slot="dropdown-menu-label"
      data-inset={inset}
      className={cn('px-2 py-1.5 text-xs font-medium text-fg-muted data-[inset]:pl-8', className)}
      {...props}
    />
  )
}

function DropdownMenuSeparator({
  className,
  ...props
}: React.ComponentProps<typeof DropdownMenuPrimitive.Separator>) {
  return (
    <DropdownMenuPrimitive.Separator
      data-slot="dropdown-menu-separator"
      className={cn('pointer-events-none -mx-1 my-1 h-px bg-border', className)}
      {...props}
    />
  )
}

/**
 * `font-mono` so `⌘⇧M` and `⌘K` line up column-wise down the menu, and
 * `text-fg-subtle` (5.47:1 / 5.77:1) because a shortcut is a reminder rather than
 * part of the command.
 *
 * The generated `tracking-widest` is dropped. It was letter-spacing applied to
 * symbols that are already one glyph wide, which pushed `⌘⇧M` apart into three
 * unrelated marks.
 *
 * This renders text only — it does not register anything. The keyboard registry in
 * `src/keyboard/` is the single source of truth for what a shortcut actually does,
 * and a label here that disagrees with it is a bug the `?` sheet will expose.
 */
function DropdownMenuShortcut({ className, ...props }: React.ComponentProps<'span'>) {
  return (
    <span
      data-slot="dropdown-menu-shortcut"
      className={cn('ml-auto font-mono text-xs text-fg-subtle', className)}
      {...props}
    />
  )
}

function DropdownMenuSub({ ...props }: React.ComponentProps<typeof DropdownMenuPrimitive.Sub>) {
  return <DropdownMenuPrimitive.Sub data-slot="dropdown-menu-sub" {...props} />
}

function DropdownMenuSubTrigger({
  className,
  inset,
  children,
  ...props
}: React.ComponentProps<typeof DropdownMenuPrimitive.SubTrigger> & {
  inset?: boolean | undefined
}) {
  return (
    <DropdownMenuPrimitive.SubTrigger
      data-slot="dropdown-menu-sub-trigger"
      data-inset={inset}
      className={cn(menuItemBase, 'data-[state=open]:bg-surface-3', className)}
      {...props}
    >
      {children}
      <ChevronRight aria-hidden="true" className="ml-auto" />
    </DropdownMenuPrimitive.SubTrigger>
  )
}

function DropdownMenuSubContent({
  className,
  ...props
}: React.ComponentProps<typeof DropdownMenuPrimitive.SubContent>) {
  return (
    <DropdownMenuPrimitive.SubContent
      data-slot="dropdown-menu-sub-content"
      className={cn(
        'z-40 min-w-40 origin-(--radix-dropdown-menu-content-transform-origin)',
        'overflow-hidden rounded-card border border-border bg-surface p-1 text-fg shadow-overlay',
        'data-[state=open]:animate-pop-in data-[state=closed]:animate-pop-out',
        'data-[side=bottom]:pop-from-top data-[side=top]:pop-from-bottom',
        'data-[side=left]:pop-from-right data-[side=right]:pop-from-left',
        className,
      )}
      {...props}
    />
  )
}

export {
  DropdownMenu,
  DropdownMenuCheckboxItem,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuPortal,
  DropdownMenuRadioGroup,
  DropdownMenuRadioItem,
  DropdownMenuSeparator,
  DropdownMenuShortcut,
  DropdownMenuSub,
  DropdownMenuSubContent,
  DropdownMenuSubTrigger,
  DropdownMenuTrigger,
}
