import { cva, type VariantProps } from 'class-variance-authority'
import type * as React from 'react'
import { cn } from '@/lib/cn'

/**
 * Generated by `shadcn add input`, then retuned. README.md has the mapping.
 *
 * `h-8` (32px) on the same ladder as Button and SelectTrigger, so a filter row
 * of a search box, a select and a button has one baseline.
 *
 * `bg-surface`, not the generated `bg-transparent`. A transparent input inherits
 * whatever is behind it, so the same field reads as sunken on `canvas` and flush
 * on `surface` — two different controls from one component. Callers that want the
 * quieter fill pass `bg-surface-2`, which is the reference's search-field look.
 *
 * `border-border-control` carries the SC 1.4.11 requirement: a text field's
 * boundary is the only thing that says where to click, so it needs 3:1 against
 * its surroundings. It measures 4.03:1 light and 3.99:1 dark on `surface`, and
 * 3.79:1 / 3.63:1 on the `bg-surface-2` fill above — both cases matter, which is
 * why the token was retuned. Before that, a `bg-surface-2` search field in dark
 * mode had a 2.48:1 boundary and no compliant edge at all. Decorative `border`
 * (`#e2e6eb`) is 1.3:1 and would fail everywhere.
 *
 * Two generated declarations are gone. `md:text-sm` was an iOS zoom workaround
 * and is a responsive decision, not a stray breakpoint here (README §5).
 * `focus-visible:ring-[3px]` is an arbitrary value the lint rule rejects, and the
 * global focus outline replaces it — `focus-visible:border-ring` stays, because
 * tinting an edge that already exists is not a second indicator.
 *
 * ### Why there is a `size` variant now
 *
 * There was not one, and the height was a hardcoded `h-8`. README §3 says the
 * ladder is shared by button, input and select trigger *"so a filter row lines up
 * without per-component nudging"* — but with no `sm` rung here, the 28px filter bar
 * in the reference could only be built by passing `className="h-7 text-sm"` at
 * every call site. That is per-component nudging with extra steps, and it is the
 * exact shape AGENTS.md forbids: a local override repeated until the design system
 * stops being one. Measured in the gallery's "one ladder, four components" row,
 * where the button, the icon button and the select trigger were 28px and the input
 * was 32.
 *
 * The variant names are `sm` / `default`, matching `SelectTrigger` rather than
 * `Button`'s `sm` / `md`. Those two are the pair that must agree — they sit beside
 * each other in every filter bar — and `SelectTrigger` set the spelling first.
 * Inventing a third one here to be closer to `Button` would leave two of the three
 * disagreeing either way.
 *
 * ### `size` shadows a real HTML attribute, and that is the cost
 *
 * `<input size>` is a native attribute — the visible width in characters, valid on
 * `text`, `search`, `url`, `tel`, `email` and `password` — so the `Omit` below takes
 * it away from every caller. That is worth stating rather than leaving as a type
 * detail, because `<Input size="sm" />` and `<Input size={20} />` look equally
 * reasonable and only one of them now compiles.
 *
 * It costs nothing here, and this is measured rather than assumed. The base above
 * always emits `w-full`, and a CSS width beats the attribute. In a 200px container:
 *
 *   with `w-full`   size absent → 200px   size="2" → 200px   size="80" → 200px
 *   without it      size absent → 145px   size="2" →  20px   size="80" → 566px
 *
 * So the attribute was already inert on every `Input` in the app before the variant
 * existed. If a caller ever genuinely needs character-based sizing it needs `w-auto`
 * as well, at which point it is a `className` on a component that stopped being
 * full-width — a different decision, not a lost prop.
 */
const inputVariants = cva(
  [
    'w-full min-w-0 rounded-control border border-border-control bg-surface',
    'text-fg shadow-xs transition-colors duration-90 ease-out',
    'placeholder:text-fg-subtle',
    'selection:bg-primary-soft selection:text-primary-soft-fg',
    // A file input's own button is a second control inside the field, so it
    // gets the field's text colour and none of its chrome.
    'file:inline-flex file:border-0 file:bg-transparent file:font-medium file:text-fg',
    'focus-visible:border-ring',
    'disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50',
    'aria-invalid:border-danger-accent',
  ],
  {
    variants: {
      size: {
        sm: 'h-7 px-2.5 text-sm file:h-5 file:text-xs',
        default: 'h-8 px-2.5 text-base file:h-6 file:text-sm',
      },
    },
    defaultVariants: { size: 'default' },
  },
)

function Input({
  className,
  type,
  size,
  ...props
}: Omit<React.ComponentProps<'input'>, 'size'> & VariantProps<typeof inputVariants>) {
  return (
    <input
      type={type}
      data-slot="input"
      data-size={size ?? 'default'}
      className={cn(inputVariants({ size }), className)}
      {...props}
    />
  )
}

export { Input, inputVariants }
