import type * as React from 'react'
import { cn } from '@/lib/cn'

/**
 * Generated by `shadcn add input`, then retuned. README.md has the mapping.
 *
 * `h-8` (32px) on the same ladder as Button and SelectTrigger, so a filter row
 * of a search box, a select and a button has one baseline.
 *
 * `bg-surface`, not the generated `bg-transparent`. A transparent input inherits
 * whatever is behind it, so the same field reads as sunken on `canvas` and flush
 * on `surface` — two different controls from one component. Callers that want the
 * quieter fill pass `bg-surface-2`, which is the reference's search-field look.
 *
 * `border-border-control` carries the SC 1.4.11 requirement: a text field's
 * boundary is the only thing that says where to click, so it needs 3:1 against
 * its surroundings. It measures 3.05:1 light and 4.0:1 dark. Decorative `border`
 * (`#e2e6eb`) is 1.3:1 and would fail.
 *
 * Two generated declarations are gone. `md:text-sm` was an iOS zoom workaround
 * and is a responsive decision, not a stray breakpoint here (README §5).
 * `focus-visible:ring-[3px]` is an arbitrary value the lint rule rejects, and the
 * global focus outline replaces it — `focus-visible:border-ring` stays, because
 * tinting an edge that already exists is not a second indicator.
 */
function Input({ className, type, ...props }: React.ComponentProps<'input'>) {
  return (
    <input
      type={type}
      data-slot="input"
      className={cn(
        'h-8 w-full min-w-0 rounded-control border border-border-control bg-surface px-2.5',
        'text-base text-fg shadow-xs transition-colors duration-90 ease-out',
        'placeholder:text-fg-subtle',
        'selection:bg-primary-soft selection:text-primary-soft-fg',
        // A file input's own button is a second control inside the field, so it
        // gets the field's text colour and none of its chrome.
        'file:inline-flex file:h-6 file:border-0 file:bg-transparent file:text-sm',
        'file:font-medium file:text-fg',
        'focus-visible:border-ring',
        'disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50',
        'aria-invalid:border-danger-accent',
        className,
      )}
      {...props}
    />
  )
}

export { Input }
