import { Label as LabelPrimitive } from 'radix-ui'
import type * as React from 'react'
import { cn } from '@/lib/cn'

/**
 * Generated by `shadcn add label`, then retuned. README.md has the mapping.
 *
 * `text-sm` (12px here, not 14px) with an explicit `text-fg`: the generated
 * version inherited its colour, which meant a label inside a `text-fg-muted`
 * block quietly became muted too, and a field label is not secondary text.
 *
 * This is the *form* label. The reference UI's tiny uppercase section headings
 * (`DETAILS`, `DATES`, `DESCRIPTION`) are a different thing and belong to
 * whichever surface draws them — `text-2xs uppercase text-fg-subtle`, which the
 * `--text-2xs` token already carries the tracking and weight for.
 *
 * Both `disabled` reach-arounds are kept from the generated code and both are
 * load-bearing: `group-data-[disabled=true]` for a Field wrapper that knows its
 * control is disabled, `peer-disabled` for a label that is a sibling of the input.
 */
function Label({ className, ...props }: React.ComponentProps<typeof LabelPrimitive.Root>) {
  return (
    <LabelPrimitive.Root
      data-slot="label"
      className={cn(
        'flex items-center gap-2 text-sm leading-none font-medium text-fg select-none',
        'group-data-[disabled=true]:pointer-events-none group-data-[disabled=true]:opacity-50',
        'peer-disabled:cursor-not-allowed peer-disabled:opacity-50',
        className,
      )}
      {...props}
    />
  )
}

export { Label }
