import { Popover as PopoverPrimitive } from 'radix-ui'
import type * as React from 'react'
import { cn } from '@/lib/cn'

/**
 * Generated by `shadcn add popover`, then retuned. README.md has the mapping.
 *
 * `z-40` — the dropdown / select / popover layer. A popover is anchored chrome, so
 * it sits below a dialog (50) and below a tooltip (60), which can be triggered by
 * a control *inside* it. The generated `z-50` collided with the dialog overlay.
 *
 * `rounded-card border-border bg-surface shadow-overlay`, replacing `rounded-md
 * border bg-popover shadow-md`. A floating layer here is a surface plus an
 * elevation, not its own colour — `shadow-overlay` is what says "above", and
 * `bg-popover` would have been a fourth near-white that has to be kept in step
 * with the other three by hand.
 *
 * `p-3` (12px) rather than `p-4`. The reference's popovers are working chrome —
 * a filter list, a date picker, an assignee search — and 16px of padding around a
 * 200px panel spends a twelfth of it on air.
 *
 * **`outline-hidden` is gone, and this one mattered.** Radix moves focus into the
 * content when a popover opens, so the generated class removed the focus
 * indicator from exactly the element that receives focus — and because utilities
 * are in a later cascade layer than `@layer base`, it beat the global
 * `:focus-visible` rule rather than losing to it.
 *
 * **Labelling is the caller's job and is not optional — and `PopoverContentProps`
 * below makes it a type error rather than a paragraph.**
 */
function Popover({ ...props }: React.ComponentProps<typeof PopoverPrimitive.Root>) {
  return <PopoverPrimitive.Root data-slot="popover" {...props} />
}

function PopoverTrigger({ ...props }: React.ComponentProps<typeof PopoverPrimitive.Trigger>) {
  return <PopoverPrimitive.Trigger data-slot="popover-trigger" {...props} />
}

/**
 * ### A popover must carry a label, and this is where that stops being advice
 *
 * Radix gives the content `role="dialog"`, and a dialog with no accessible name is
 * announced as "dialog" and nothing else. The gap is not symmetrical with `Dialog`,
 * and the asymmetry is measured rather than assumed:
 *
 * - `@radix-ui/react-dialog@1.1.23` wires `"aria-labelledby": context.titlePresent ?
 *   context.titleId : void 0` (dist/index.mjs:233) — a dialog labels itself from its
 *   own `Title`, so forgetting one is caught by Radix's own dev warning.
 * - `@radix-ui/react-popover@1.1.23` sets `role="dialog"` (dist/index.mjs:245) and
 *   wires **no** labelling attribute at all, and warns about nothing.
 *
 * So a popover inherits the strictest role in the library with none of the machinery,
 * and until now the gap was covered by a paragraph in this file's header — which only
 * helps a caller who read it. The union below moves the check to the compiler, at the
 * call site, where the person who knows what the popover is *for* is standing.
 *
 * Exactly one of the two, not "at least one". Passing both is rejected on purpose:
 * `aria-labelledby` wins in the accessible-name algorithm, so an element carrying
 * both has a label that does nothing and no indication of which one lost.
 *
 * `?: undefined` rather than `?: never` on the absent side, because
 * `exactOptionalPropertyTypes` is on: `?: never` would reject a caller forwarding its
 * own `string | undefined` even when the value is genuinely absent, which is a real
 * pattern and not a mistake. `?: undefined` accepts the absence and still rejects a
 * string.
 *
 * Not done, deliberately: auto-generating an `aria-labelledby` pointing at a
 * `PopoverTitle` the caller may not have rendered. That resolves to an empty string,
 * which is worse than an unlabelled dialog because it looks handled — to axe as much
 * as to a reviewer.
 */
type PopoverContentProps = Omit<
  React.ComponentProps<typeof PopoverPrimitive.Content>,
  'aria-label' | 'aria-labelledby'
> &
  (
    | { 'aria-label': string; 'aria-labelledby'?: undefined }
    | { 'aria-labelledby': string; 'aria-label'?: undefined }
  )

function PopoverContent({
  className,
  align = 'center',
  sideOffset = 4,
  ...props
}: PopoverContentProps) {
  return (
    <PopoverPrimitive.Portal>
      <PopoverPrimitive.Content
        data-slot="popover-content"
        align={align}
        sideOffset={sideOffset}
        className={cn(
          'z-40 w-72 origin-(--radix-popover-content-transform-origin)',
          'rounded-card border border-border bg-surface p-3 text-fg shadow-overlay',
          'data-[state=open]:animate-pop-in data-[state=closed]:animate-pop-out',
          'data-[side=bottom]:pop-from-top data-[side=top]:pop-from-bottom',
          'data-[side=left]:pop-from-right data-[side=right]:pop-from-left',
          className,
        )}
        {...props}
      />
    </PopoverPrimitive.Portal>
  )
}

function PopoverAnchor({ ...props }: React.ComponentProps<typeof PopoverPrimitive.Anchor>) {
  return <PopoverPrimitive.Anchor data-slot="popover-anchor" {...props} />
}

function PopoverHeader({ className, ...props }: React.ComponentProps<'div'>) {
  return (
    <div
      data-slot="popover-header"
      className={cn('flex flex-col gap-1 pb-2', className)}
      {...props}
    />
  )
}

/**
 * Renders an `h2`, which is what the generated version's *type* claimed and its
 * *element* did not — it was typed `ComponentProps<'h2'>` and rendered a `div`, so
 * a caller passing a heading-only attribute got no type error and no heading.
 *
 * `children` is destructured and placed explicitly rather than arriving through the
 * spread. That is not a style preference: `jsx-a11y/heading-has-content` reads the
 * JSX, and a heading whose content comes from `{...props}` looks empty to it. The
 * rule is right to complain — `<PopoverTitle />` with no children compiles fine and
 * renders an empty `h2`, which is a heading in the document outline with nothing in
 * it. Writing the child out makes the rule able to check it.
 */
function PopoverTitle({ className, children, ...props }: React.ComponentProps<'h2'>) {
  return (
    <h2
      data-slot="popover-title"
      className={cn('text-base font-medium text-fg', className)}
      {...props}
    >
      {children}
    </h2>
  )
}

function PopoverDescription({ className, ...props }: React.ComponentProps<'p'>) {
  return (
    <p
      data-slot="popover-description"
      className={cn('text-sm text-fg-muted', className)}
      {...props}
    />
  )
}

export {
  Popover,
  PopoverAnchor,
  PopoverContent,
  PopoverDescription,
  PopoverHeader,
  PopoverTitle,
  PopoverTrigger,
}
export type { PopoverContentProps }
