import { RadioGroup as RadioGroupPrimitive } from 'radix-ui'
import type * as React from 'react'
import { cn } from '@/lib/cn'

/**
 * Generated by `shadcn add radio-group`, then retuned. README.md has the mapping.
 *
 * The checked state fills, exactly like Checkbox: `border-primary bg-primary`
 * with a white dot inside. The generated version instead kept the unchecked
 * border and drew a violet dot on the surface. Both are legible, but a form with
 * both control types in it should not have one of them announce selection by
 * filling and the other by adding a speck — README §8 is the reason, and the
 * practical payoff is that "which of these is on" is answerable from across the
 * screen rather than by reading each row.
 *
 * The dot measures 6px (`size-1.5`) inside a 14px interior, so 4px of violet
 * shows on each side. White on `primary` is **5.15:1** in both themes.
 *
 * `CircleIcon` is gone. It was a lucide import, absolutely positioned with
 * `-translate-x-1/2 -translate-y-1/2` and `fill-primary`, to draw a filled
 * circle — which is a `span` with a background and a border radius. The Indicator
 * is already a flex centring box, so the offsets were doing nothing the layout
 * was not.
 *
 * `outline-none` is gone for the reason in checkbox.tsx: a utility layer beats
 * `@layer base`, so leaving it would have silently removed the global focus
 * outline from every radio in the product.
 *
 * `gap-3` (12px) on the group is unchanged, and is the value for a stack of
 * label-bearing rows. A dense inline group — a segmented "sort by" — should pass
 * `className="flex gap-4"` rather than have a variant, because the two cases have
 * nothing in common but the primitive.
 */
function RadioGroup({
  className,
  ...props
}: React.ComponentProps<typeof RadioGroupPrimitive.Root>) {
  return (
    <RadioGroupPrimitive.Root
      data-slot="radio-group"
      className={cn('grid gap-3', className)}
      {...props}
    />
  )
}

/**
 * The `before:` pseudo-element is hit area only — 16px visual, 24x24 target, as
 * WCAG 2.2 SC 2.5.8 asks. See checkbox.tsx.
 */
function RadioGroupItem({
  className,
  ...props
}: React.ComponentProps<typeof RadioGroupPrimitive.Item>) {
  return (
    <RadioGroupPrimitive.Item
      data-slot="radio-group-item"
      className={cn(
        'relative aspect-square size-4 shrink-0 rounded-chip',
        'border border-border-control bg-surface shadow-xs',
        'transition-colors duration-90 ease-out',
        'before:absolute before:-inset-1',
        'data-[state=checked]:border-primary data-[state=checked]:bg-primary',
        'aria-invalid:border-danger-accent',
        'disabled:cursor-not-allowed disabled:opacity-50',
        className,
      )}
      {...props}
    >
      <RadioGroupPrimitive.Indicator
        data-slot="radio-group-indicator"
        className="flex size-full items-center justify-center"
      >
        <span className="size-1.5 rounded-chip bg-primary-fg" />
      </RadioGroupPrimitive.Indicator>
    </RadioGroupPrimitive.Item>
  )
}

export { RadioGroup, RadioGroupItem }
