import { ScrollArea as ScrollAreaPrimitive } from 'radix-ui'
import type * as React from 'react'
import { cn } from '@/lib/cn'

/**
 * Generated by `shadcn add scroll-area`, then retuned. README.md has the mapping.
 *
 * **Read this before reaching for it.** This is not the default way to make
 * something scroll in flux. `tokens.css` already styles the *native* scrollbar
 * slim and theme-aware, so `overflow-y-auto` gets the same look with none of the
 * cost. Radix's ScrollArea replaces the native scrollbar with JavaScript-driven
 * elements, and that means a ResizeObserver per instance, layout reads on scroll,
 * and the loss of platform behaviour users do not consciously notice until it is
 * gone: momentum, rubber-banding, scroll anchoring, and the OS setting that shows
 * scrollbars always rather than on scroll.
 *
 * So: the board, the backlog and every virtualised list use native overflow.
 * This component is for a *constrained popover* — a select with forty options, a
 * filter list inside a dropdown — where the panel needs a maximum height and a
 * scrollbar that is visibly part of the panel rather than the window.
 *
 * The thumb is `bg-border-strong` with `hover:bg-fg-subtle`, which is character
 * for character what the base layer gives the native scrollbar
 * (`scrollbar-color: var(--color-border-strong) transparent`). Matching matters
 * more here than a contrast argument would: two scrollbar treatments in one app
 * is the visible kind of inconsistency, and a scrollbar is never the only way to
 * reach content — wheel, trackpad, arrow keys, Page Up/Down and typeahead all
 * work without it.
 *
 * Dropped from the generated version: `outline-none` (it would beat the global
 * `:focus-visible` rule, which sits in an earlier cascade layer),
 * `focus-visible:ring-[3px]` (an arbitrary value the lint rule rejects), and
 * `rounded-[inherit]` — the same declaration is now the `rounded-inherit` utility
 * in `tokens.css`, because the lint rule cannot distinguish a real `inherit` from
 * a hard-coded radius and should not have to.
 */
function ScrollArea({
  className,
  children,
  ...props
}: React.ComponentProps<typeof ScrollAreaPrimitive.Root>) {
  return (
    <ScrollAreaPrimitive.Root
      data-slot="scroll-area"
      className={cn('relative', className)}
      {...props}
    >
      <ScrollAreaPrimitive.Viewport
        data-slot="scroll-area-viewport"
        className="size-full rounded-inherit"
      >
        {children}
      </ScrollAreaPrimitive.Viewport>
      <ScrollBar />
      <ScrollAreaPrimitive.Corner />
    </ScrollAreaPrimitive.Root>
  )
}

/**
 * `w-2.5` (10px) matches the `::-webkit-scrollbar` width in the base layer, so a
 * ScrollArea inside a natively-scrolling parent does not step down in weight.
 *
 * `p-px` is what leaves the 8px thumb inside a 10px gutter rather than filling it.
 */
function ScrollBar({
  className,
  orientation = 'vertical',
  ...props
}: React.ComponentProps<typeof ScrollAreaPrimitive.ScrollAreaScrollbar>) {
  return (
    <ScrollAreaPrimitive.ScrollAreaScrollbar
      data-slot="scroll-area-scrollbar"
      orientation={orientation}
      className={cn(
        'flex touch-none p-px transition-colors duration-90 ease-out select-none',
        orientation === 'vertical' && 'h-full w-2.5 border-l border-l-transparent',
        orientation === 'horizontal' && 'h-2.5 flex-col border-t border-t-transparent',
        className,
      )}
      {...props}
    >
      <ScrollAreaPrimitive.ScrollAreaThumb
        data-slot="scroll-area-thumb"
        className="relative flex-1 rounded-chip bg-border-strong transition-colors duration-90 ease-out hover:bg-fg-subtle"
      />
    </ScrollAreaPrimitive.ScrollAreaScrollbar>
  )
}

export { ScrollArea, ScrollBar }
