import { cva, type VariantProps } from 'class-variance-authority'
import { Check, ChevronDown, ChevronUp } from 'lucide-react'
import { Select as SelectPrimitive } from 'radix-ui'
import type * as React from 'react'
import { cn } from '@/lib/cn'

/**
 * Generated by `shadcn add select`, then retuned. README.md has the mapping.
 *
 * **This is a select, not a combobox.** It has no text input, so it cannot be
 * typed into and cannot be filtered — Radix gives it single-character type-ahead
 * and nothing more. That makes it right for a closed list a person can scan
 * (status, priority, issue type, a workflow's four status categories) and wrong
 * for anything that grows: assignee, label, sprint, parent issue, project. Those
 * need the command palette pattern, and reaching for `Select` there produces the
 * 400-option scroll that is one of the Jira behaviours we are replacing. The rule
 * of thumb: if the list can exceed roughly a dozen entries in a real
 * organisation, it is not this component.
 *
 * Four changes are behavioural rather than cosmetic:
 *
 * 1. **`position` defaults to `popper`, not `item-aligned`.** `item-aligned`
 *    reproduces a native `<select>`, overlaying the trigger and aligning the
 *    chosen row on top of it. It also ignores `side`, `sideOffset` and
 *    `--radix-select-content-transform-origin`, which is why the generated file's
 *    `data-[side=…]` and `origin-(…)` classes never applied to anything. `popper`
 *    anchors below the trigger like every other menu in the product, so a select
 *    and a dropdown menu no longer open in two different ways.
 * 2. **The viewport's `h-[var(--radix-select-trigger-height)]` is gone.** It set
 *    the scrolling viewport to exactly one trigger-height, so an eight-option menu
 *    rendered as a one-row scroll box. `min-w-(--radix-select-trigger-width)`
 *    stays — matching the trigger's width is genuinely wanted.
 * 3. **The trigger is `w-full`, not `w-fit`.** `w-fit` sizes the control to its
 *    current value, so picking "In Progress" after "To Do" makes the control grow
 *    and shoves whatever is beside it sideways. A control that changes size when
 *    you use it is the kind of small instability §7 rules out. Callers that want a
 *    narrow select pass `className="w-40"` and get a stable width.
 * 4. **`line-clamp-1` and `flex` are no longer both applied to the value.**
 *    `line-clamp-1` sets `display: -webkit-box` and `flex` sets `display: flex`;
 *    whichever won, the other's purpose was lost. What was wanted is an ellipsis
 *    on a long value, which is `min-w-0 truncate` — and `min-w-0` is the half that
 *    makes it work at all inside a flex trigger.
 *
 * Also: `outline-none focus-visible:ring-[3px]` is gone (the global
 * `:focus-visible` ring in `@layer base` is the product's one focus treatment, and
 * `ring-[3px]` was a lint error besides), `opacity-50` on the chevron became
 * `text-fg-muted` so the icon is a colour rather than a faded copy of the border,
 * and every `dark:` colour variant is gone because the tokens already flip.
 */
function Select({ ...props }: React.ComponentProps<typeof SelectPrimitive.Root>) {
  return <SelectPrimitive.Root data-slot="select" {...props} />
}

function SelectGroup({ ...props }: React.ComponentProps<typeof SelectPrimitive.Group>) {
  return <SelectPrimitive.Group data-slot="select-group" {...props} />
}

function SelectValue({ ...props }: React.ComponentProps<typeof SelectPrimitive.Value>) {
  return <SelectPrimitive.Value data-slot="select-value" {...props} />
}

/**
 * Two heights off README §2's control ladder — `default` is 32px with 12px of
 * horizontal padding, `sm` is 28px with 10px. There is no `lg`: a 40px select is
 * a marketing-page control, and inside the app a taller field would break the
 * row rhythm every table and toolbar is built on.
 *
 * `data-[placeholder]:text-fg-subtle` is 5.47:1 light / 5.77:1 dark, so the
 * unselected state ("Select a status") is real readable text and not the 2:1 grey
 * that placeholders usually get.
 */
const selectTrigger = cva(
  [
    'flex w-full items-center justify-between gap-2 overflow-hidden whitespace-nowrap',
    'rounded-control border border-border-control bg-surface text-fg shadow-xs',
    'transition-colors duration-90 ease-out',
    'hover:bg-surface-2',
    'data-[placeholder]:text-fg-subtle',
    'disabled:cursor-not-allowed disabled:opacity-50',
    'aria-invalid:border-danger-accent',
    '*:data-[slot=select-value]:min-w-0 *:data-[slot=select-value]:truncate',
    "[&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-3.5",
  ],
  {
    variants: {
      size: {
        sm: 'h-7 px-2.5 text-sm',
        default: 'h-8 px-3 text-base',
      },
    },
    defaultVariants: { size: 'default' },
  },
)

function SelectTrigger({
  className,
  size,
  children,
  ...props
}: React.ComponentProps<typeof SelectPrimitive.Trigger> & VariantProps<typeof selectTrigger>) {
  return (
    <SelectPrimitive.Trigger
      data-slot="select-trigger"
      data-size={size ?? 'default'}
      className={cn(selectTrigger({ size }), className)}
      {...props}
    >
      {children}
      <SelectPrimitive.Icon asChild>
        <ChevronDown aria-hidden="true" className="text-fg-muted" />
      </SelectPrimitive.Icon>
    </SelectPrimitive.Trigger>
  )
}

function SelectContent({
  className,
  children,
  position = 'popper',
  sideOffset = 4,
  ...props
}: React.ComponentProps<typeof SelectPrimitive.Content>) {
  return (
    <SelectPrimitive.Portal>
      <SelectPrimitive.Content
        data-slot="select-content"
        position={position}
        sideOffset={sideOffset}
        className={cn(
          'relative z-40 min-w-32 max-h-(--radix-select-content-available-height)',
          'origin-(--radix-select-content-transform-origin) overflow-x-hidden overflow-y-auto',
          'rounded-card border border-border bg-surface text-fg shadow-overlay',
          'data-[state=open]:animate-pop-in data-[state=closed]:animate-pop-out',
          'data-[side=bottom]:pop-from-top data-[side=top]:pop-from-bottom',
          'data-[side=left]:pop-from-right data-[side=right]:pop-from-left',
          className,
        )}
        {...props}
      >
        <SelectScrollUpButton />
        <SelectPrimitive.Viewport
          className={cn(
            'p-1',
            position === 'popper' && 'w-full min-w-(--radix-select-trigger-width) scroll-my-1',
          )}
        >
          {children}
        </SelectPrimitive.Viewport>
        <SelectScrollDownButton />
      </SelectPrimitive.Content>
    </SelectPrimitive.Portal>
  )
}

function SelectLabel({ className, ...props }: React.ComponentProps<typeof SelectPrimitive.Label>) {
  return (
    <SelectPrimitive.Label
      data-slot="select-label"
      className={cn('px-2 py-1.5 text-xs font-medium text-fg-muted', className)}
      {...props}
    />
  )
}

/**
 * The selected row is marked three ways: `aria-selected` for assistive
 * technology, `font-medium`, and the check. Colour is the fourth, not the first —
 * `text-primary-accent` on the check measures 5.84:1 light / 6.13:1 dark, where
 * plain `text-primary` would be 3.45:1 in dark and would be carrying the meaning
 * on its own.
 *
 * `focus:bg-surface-3` is the highlight; the `-outline-offset-2` matters because
 * the content is an `overflow-y-auto` box, so an outline drawn outside an item's
 * border would be clipped by the scroll container on the first and last rows.
 * Drawing it inside keeps the whole ring visible wherever the item sits.
 */
function SelectItem({
  className,
  children,
  ...props
}: React.ComponentProps<typeof SelectPrimitive.Item>) {
  return (
    <SelectPrimitive.Item
      data-slot="select-item"
      className={cn(
        'relative flex w-full cursor-default items-center gap-2 select-none',
        'rounded-control py-1.5 pr-8 pl-2 text-base',
        'focus:bg-surface-3 focus-visible:-outline-offset-2',
        'data-[state=checked]:font-medium',
        'data-[disabled]:pointer-events-none data-[disabled]:opacity-50',
        "[&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-3.5",
        className,
      )}
      {...props}
    >
      <span
        data-slot="select-item-indicator"
        className="pointer-events-none absolute right-2 flex size-3.5 items-center justify-center"
      >
        <SelectPrimitive.ItemIndicator>
          <Check aria-hidden="true" className="text-primary-accent" />
        </SelectPrimitive.ItemIndicator>
      </span>
      <SelectPrimitive.ItemText>{children}</SelectPrimitive.ItemText>
    </SelectPrimitive.Item>
  )
}

function SelectSeparator({
  className,
  ...props
}: React.ComponentProps<typeof SelectPrimitive.Separator>) {
  return (
    <SelectPrimitive.Separator
      data-slot="select-separator"
      className={cn('pointer-events-none -mx-1 my-1 h-px bg-border', className)}
      {...props}
    />
  )
}

function SelectScrollUpButton({
  className,
  ...props
}: React.ComponentProps<typeof SelectPrimitive.ScrollUpButton>) {
  return (
    <SelectPrimitive.ScrollUpButton
      data-slot="select-scroll-up-button"
      className={cn(
        'flex cursor-default items-center justify-center py-1 text-fg-muted',
        className,
      )}
      {...props}
    >
      <ChevronUp aria-hidden="true" className="size-3.5" />
    </SelectPrimitive.ScrollUpButton>
  )
}

function SelectScrollDownButton({
  className,
  ...props
}: React.ComponentProps<typeof SelectPrimitive.ScrollDownButton>) {
  return (
    <SelectPrimitive.ScrollDownButton
      data-slot="select-scroll-down-button"
      className={cn(
        'flex cursor-default items-center justify-center py-1 text-fg-muted',
        className,
      )}
      {...props}
    >
      <ChevronDown aria-hidden="true" className="size-3.5" />
    </SelectPrimitive.ScrollDownButton>
  )
}

export {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectScrollDownButton,
  SelectScrollUpButton,
  SelectSeparator,
  SelectTrigger,
  selectTrigger,
  SelectValue,
}
export type SelectTriggerVariants = VariantProps<typeof selectTrigger>
