import { Separator as SeparatorPrimitive } from 'radix-ui'
import type * as React from 'react'
import { cn } from '@/lib/cn'

/**
 * Generated by `shadcn add separator`, then retuned. README.md has the mapping.
 *
 * `bg-border` is unchanged, and is one of the few generated colours that already
 * mapped: a separator is decorative, so it is exempt from WCAG 2.2 SC 1.4.11 and
 * `border` (#e2e6eb, 1.3:1) is the right weight. A line strong enough to pass a
 * contrast floor it does not have to pass would divide the UI more loudly than
 * the content warrants. Use `bg-border-strong` for a *structural* division —
 * sidebar from main, a table's header rule — where the line is doing real work.
 *
 * `decorative` defaults to `true`, which makes Radix render `role="none"` and
 * omit it from the accessibility tree. That default is correct far more often
 * than not: a line between two groups is a visual restatement of grouping that
 * the heading structure should already carry. Pass `decorative={false}` only
 * when the separator is the *only* thing communicating the boundary, in which
 * case it becomes `role="separator"` and is announced.
 *
 * `"use client"` is gone from every file in this directory. It is a Next.js
 * directive; this is a Vite SPA and there is no server component boundary for it
 * to mark.
 */
function Separator({
  className,
  orientation = 'horizontal',
  decorative = true,
  ...props
}: React.ComponentProps<typeof SeparatorPrimitive.Root>) {
  return (
    <SeparatorPrimitive.Root
      data-slot="separator"
      decorative={decorative}
      orientation={orientation}
      className={cn(
        'shrink-0 bg-border',
        'data-[orientation=horizontal]:h-px data-[orientation=horizontal]:w-full',
        'data-[orientation=vertical]:h-full data-[orientation=vertical]:w-px',
        className,
      )}
      {...props}
    />
  )
}

export { Separator }
