import type * as React from 'react'
import { cn } from '@/lib/cn'

/**
 * Generated by `shadcn add skeleton`, then retuned. README.md has the mapping.
 *
 * `bg-surface-3` rather than the generated `bg-accent`. It is the same step in
 * the surface ladder that a hover fill uses, which is the right weight: a
 * skeleton should read as "content is coming" and not as a filled block that
 * looks like a real UI element.
 *
 * `rounded-card` (12px), matching the card the content will land in. A skeleton
 * whose corners differ from its replacement makes the swap visible as a shape
 * change on top of a content change.
 *
 * `aria-hidden`, and this is the important part. A skeleton carries no
 * information — a screen reader announcing four empty boxes is worse than
 * silence. The *surface* owns the announcement: it marks its loading region
 * `aria-busy="true"` and, once loaded, moves focus or announces the result. If a
 * caller genuinely needs the box in the tree it can pass `aria-hidden={false}`,
 * but it almost certainly wants `aria-busy` on the container instead.
 *
 * `animate-pulse` is Tailwind's own, not one of ours — the `--animate-*` tokens
 * in `tokens.css` are one-shot enter/exit animations and this one loops. Under
 * `prefers-reduced-motion` the base layer clamps it with
 * `animation-iteration-count: 1`, so it settles at full opacity rather than
 * strobing at 1ms intervals, which is what clamping only the duration would do.
 */
function Skeleton({ className, ...props }: React.ComponentProps<'div'>) {
  return (
    <div
      data-slot="skeleton"
      aria-hidden="true"
      className={cn('animate-pulse rounded-card bg-surface-3', className)}
      {...props}
    />
  )
}

export { Skeleton }
