import type * as React from 'react'
import { cn } from '@/lib/cn'

/**
 * Generated by `shadcn add skeleton`, then retuned. README.md has the mapping.
 *
 * `bg-surface-3` rather than the generated `bg-accent`. It is the same step in
 * the surface ladder that a hover fill uses, which is the right weight: a
 * skeleton should read as "content is coming" and not as a filled block that
 * looks like a real UI element.
 *
 * `rounded-card` (12px), matching the card the content will land in. A skeleton
 * whose corners differ from its replacement makes the swap visible as a shape
 * change on top of a content change.
 *
 * `aria-hidden`, and this is the important part. A skeleton carries no
 * information — a screen reader announcing four empty boxes is worse than
 * silence. The *surface* owns the announcement: it marks its loading region
 * `aria-busy="true"` and, once loaded, moves focus or announces the result. If a
 * caller genuinely needs the box in the tree it can pass `aria-hidden={false}`,
 * but it almost certainly wants `aria-busy` on the container instead.
 *
 * `animate-pulse` is Tailwind's own, not one of ours — the `--animate-*` tokens
 * in `tokens.css` are one-shot enter/exit animations and this one loops. Under
 * `prefers-reduced-motion` the base layer clamps it with
 * `animation-iteration-count: 1`, so it settles at full opacity rather than
 * strobing at 1ms intervals, which is what clamping only the duration would do.
 */
function Skeleton({ className, ...props }: React.ComponentProps<'div'>) {
  return (
    <div
      data-slot="skeleton"
      aria-hidden="true"
      className={cn('animate-pulse rounded-card bg-surface-3', className)}
      {...props}
    />
  )
}

/**
 * A skeleton exactly one line of text tall.
 *
 * ### The problem it solves
 *
 * "A skeleton must occupy exactly the box its real content will, or the page jumps
 * when data lands" is easy to state and, with a plain `Skeleton`, is guesswork: the
 * caller picks `h-3.5` or `h-4` for a line of body text and is wrong by a couple of
 * pixels per line. Measured in the gallery on a two-line list row, the loading
 * state came out **58px against the loaded row's 70** — a 12px jump on every row of
 * a list, which is the exact failure the rule exists to prevent, produced by a
 * caller following the rule as written.
 *
 * `h-[1lh]` is the fix, and it is not a magic number: `lh` is the CSS unit for *one
 * line box of the current element's line-height*. Because the height is inherited
 * rather than chosen, a `SkeletonText` inside a `text-base` block is one line of
 * body text, and inside a `text-sm` block it is one line of small text, with
 * nothing to keep in step. Change the type scale and this follows.
 *
 * The arbitrary value is deliberate and permitted: `h-` is on the layout side of
 * the lint rule's exemption list, precisely because geometry sometimes has no token
 * and this is a unit rather than a value.
 *
 * ### It does not move the browser floor
 *
 * Worth checking rather than assuming, because an unsupported `height` declaration
 * is *dropped*, and a skeleton line with no height is 0px — invisible, not degraded.
 * `lh` needs Chrome 109, Safari 16.4, Firefox 120. The stylesheet this app already
 * ships needs Chrome 111, Safari 16.4, Firefox 128, because Tailwind v4 emits
 * `@property` and `color-mix()` — counted in the served CSS: **53 `@property`
 * rules, 14 `color-mix()`, 142 `oklch()`, and 3 `1lh`.** So every browser that can
 * render a single colour in this product can already resolve this unit, and the
 * three occurrences are the least demanding thing in the file. `apps/web/README.md`
 * §"Browser floor" holds the numbers and where they come from.
 *
 * `rounded-control` rather than the block's `rounded-card`: 12px corners on a 20px
 * bar read as a lozenge, and a line of text is not a card.
 *
 * `width` stays the caller's — a skeleton line is meant to be ragged, because four
 * bars of identical width read as a table rather than as prose.
 */
function SkeletonText({ className, ...props }: React.ComponentProps<'div'>) {
  return (
    <Skeleton
      data-slot="skeleton-text"
      className={cn('h-[1lh] rounded-control', className)}
      {...props}
    />
  )
}

export { Skeleton, SkeletonText }
