import { cva, type VariantProps } from 'class-variance-authority'
import { Switch as SwitchPrimitive } from 'radix-ui'
import type * as React from 'react'
import { cn } from '@/lib/cn'

/**
 * Generated by `shadcn add switch`, then retuned. README.md has the mapping.
 *
 * The generated geometry was `h-[1.15rem] w-8` with the thumb travelling
 * `translate-x-[calc(100%-2px)]` — three arbitrary values, two of which the lint
 * rule rejects, and 1.15rem is 18.4px, which lands the track on a half pixel at
 * every zoom level that is not 100%. Replaced with numbers that divide:
 *
 * | Size | Track | Inset | Thumb | Travel |
 * | --- | --- | --- | --- | --- |
 * | `md` | `h-4 w-7` — 16x28 | `p-0.5` 2px | `size-3` 12px | 28 − 2 − 2 − 12 = **12px** = `translate-x-3` |
 * | `sm` | `h-3.5 w-6` — 14x24 | `p-0.5` 2px | `size-2.5` 10px | 24 − 2 − 2 − 10 = **10px** = `translate-x-2.5` |
 *
 * `p-0.5` does the vertical centring as well as the horizontal inset: a 16px
 * track minus 2px of padding top and bottom is a 12px content box, which is
 * exactly the thumb, so the thumb cannot drift off centre at any zoom.
 *
 * Colours are measured, and per state rather than per theme — there is no `dark:`
 * variant here, unlike the five the generator emitted:
 *
 * - Off track `bg-neutral-solid` — #63697a light, #8b949e dark, **5.48:1** and
 *   **5.44:1** against `surface`. Comfortably past the 3:1 that WCAG 2.2 SC
 *   1.4.11 asks of a control whose boundary carries meaning, so the track needs
 *   no border of its own to be identifiable.
 * - On track `bg-primary`.
 * - Off thumb `bg-surface`, on thumb `bg-primary-fg`. Two tokens rather than one
 *   white, because in dark mode `surface` is #1c1e1f: **5.44:1** on the off track
 *   and, if it were reused for the on state, only **3.25:1** on violet. White
 *   (`primary-fg`) is **5.15:1** on violet in both themes. So each state uses the
 *   token that measures well against the fill it actually sits on.
 *
 *   The dark pair moved when `--surface` was retuned to the reference's #1c1e1f
 *   (5.77:1 and 3.45:1 before), and the conclusion moved *further* in its favour:
 *   a lighter thumb on violet is worse, not better, so the gap between reusing
 *   `surface` and using white widened from 1.70 to 1.91.
 *
 * State is never carried by colour alone — the thumb's position is the primary
 * signal, and `role="switch"` plus `aria-checked` is what assistive technology
 * reads.
 *
 * The `before:` pseudo-element is hit area. SC 2.5.8 asks for 24x24; the visual
 * track is 16px tall (14 for `sm`), so `-inset-y-1` and `-inset-y-1.5` bring the
 * target to 24px and 26px without moving a pixel of the design.
 */
const switchTrack = cva(
  [
    'peer relative inline-flex shrink-0 items-center rounded-chip p-0.5',
    'transition-colors duration-140 ease-out',
    'before:absolute before:inset-x-0',
    'data-[state=checked]:bg-primary data-[state=unchecked]:bg-neutral-solid',
    'disabled:cursor-not-allowed disabled:opacity-50',
  ],
  {
    variants: {
      size: {
        sm: 'h-3.5 w-6 before:-inset-y-1.5',
        md: 'h-4 w-7 before:-inset-y-1',
      },
    },
    defaultVariants: { size: 'md' },
  },
)

const switchThumb = cva(
  [
    'pointer-events-none block rounded-chip shadow-xs',
    'transition-transform duration-140 ease-out',
    'data-[state=unchecked]:translate-x-0',
    'data-[state=checked]:bg-primary-fg data-[state=unchecked]:bg-surface',
  ],
  {
    variants: {
      size: {
        sm: 'size-2.5 data-[state=checked]:translate-x-2.5',
        md: 'size-3 data-[state=checked]:translate-x-3',
      },
    },
    defaultVariants: { size: 'md' },
  },
)

function Switch({
  className,
  size = 'md',
  ...props
}: React.ComponentProps<typeof SwitchPrimitive.Root> & VariantProps<typeof switchTrack>) {
  return (
    <SwitchPrimitive.Root
      data-slot="switch"
      data-size={size}
      className={cn(switchTrack({ size }), className)}
      {...props}
    >
      <SwitchPrimitive.Thumb data-slot="switch-thumb" className={switchThumb({ size })} />
    </SwitchPrimitive.Root>
  )
}

export { Switch }
