import { cva, type VariantProps } from 'class-variance-authority'
import { Tabs as TabsPrimitive } from 'radix-ui'
import * as React from 'react'
import { cn } from '@/lib/cn'

/**
 * Generated by `shadcn add tabs`, then substantially rewritten. README.md has the
 * mapping.
 *
 * Two variants, both taken off the reference UI:
 *
 * - **`solid`** — the raised segment switcher. Board / Backlog / Timeline at the
 *   top of a project; List / Board in the reference video. A 32px trough with a
 *   24px chip lifted out of it.
 * - **`line`** — underlined text tabs. The issue panel's Comments / History /
 *   Worklog, a settings section list. No fill at all, so a row of them beside a
 *   `solid` switcher does not read as two competing switchers.
 *
 * **The API differs from shadcn's in one way: `variant` is on `Tabs`, not on
 * `TabsList`.** The generated version put it on the List and then reached back
 * down to the triggers with `group-data-[variant=line]/tabs-list:` — twelve of
 * those, some of them also carrying `dark:`, in a single 900-character string that
 * cannot be read, let alone reviewed. Variant and orientation both come through
 * one context here, so each trigger's classes are just `tabsTrigger({ variant,
 * orientation })` and the two axes compose through `compoundVariants` instead of
 * through selector nesting. `TabsTrigger` is always inside `TabsList` inside
 * `Tabs` — Radix requires it — so the context cannot be missing.
 *
 * `outline-none` is gone from `TabsContent`, and that one was a real defect rather
 * than a cosmetic one: Radix gives the content panel `tabIndex={0}` so a keyboard
 * user can tab from the tab list into the panel, and `outline-none` removed the
 * only indication that they had arrived. Utilities sit in a later cascade layer
 * than `@layer base`, so it beat the global `:focus-visible` rule outright.
 */

type TabsVariant = 'solid' | 'line'
type TabsOrientation = 'horizontal' | 'vertical'

const TabsStyleContext = React.createContext<{
  variant: TabsVariant
  orientation: TabsOrientation
}>({ variant: 'solid', orientation: 'horizontal' })

function Tabs({
  className,
  variant = 'solid',
  orientation = 'horizontal',
  ...props
}: React.ComponentProps<typeof TabsPrimitive.Root> & { variant?: TabsVariant }) {
  const style = React.useMemo(() => ({ variant, orientation }), [variant, orientation])

  return (
    <TabsStyleContext.Provider value={style}>
      <TabsPrimitive.Root
        data-slot="tabs"
        data-variant={variant}
        orientation={orientation}
        className={cn(
          'flex gap-3 data-[orientation=horizontal]:flex-col',
          'data-[orientation=vertical]:flex-row',
          className,
        )}
        {...props}
      />
    </TabsStyleContext.Provider>
  )
}

/**
 * `solid`: 32px trough, `rounded-card` (12px), `p-1` (4px) — so the chip inside is
 * 24px tall with a 12 − 4 = **8px** inner radius, which is `rounded-control`.
 * That is README §3's nested-radius rule, not a coincidence.
 *
 * `line`: a 1px rule under the whole strip, which each active trigger overlaps
 * with its own 2px border via `-mb-px`. Overlapping rather than stacking is what
 * keeps the underline 2px tall instead of 3px, and keeps it aligned with the rule
 * rather than sitting a pixel below it.
 */
const tabsList = cva('inline-flex w-fit items-center', {
  variants: {
    variant: {
      solid: 'gap-0.5 rounded-card bg-surface-2 p-1',
      line: 'gap-4',
    },
    orientation: {
      horizontal: '',
      vertical: 'h-fit flex-col items-stretch',
    },
  },
  compoundVariants: [
    { variant: 'solid', orientation: 'horizontal', class: 'h-8' },
    { variant: 'line', orientation: 'horizontal', class: 'h-8 border-b border-border' },
    { variant: 'line', orientation: 'vertical', class: 'gap-1 border-l border-border' },
  ],
  defaultVariants: { variant: 'solid', orientation: 'horizontal' },
})

function TabsList({ className, ...props }: React.ComponentProps<typeof TabsPrimitive.List>) {
  const { variant, orientation } = React.useContext(TabsStyleContext)

  return (
    <TabsPrimitive.List
      data-slot="tabs-list"
      data-variant={variant}
      className={cn(tabsList({ variant, orientation }), className)}
      {...props}
    />
  )
}

/**
 * The active state is carried three ways on purpose — `aria-selected` for
 * assistive technology, a text-colour step from `fg-muted` (7.9:1) to `fg`
 * (17.8:1), and the fill or underline. That matters most for `solid`, where the
 * active chip is `raised` on a `surface-2` trough: those two measure about 1.1:1
 * against each other in light mode, because a raised segment in a light theme is
 * white on near-white and every implementation of this control has the same
 * problem. It is legitimate here only because the fill is the *third* signal
 * rather than the only one — the border and shadow give it an edge, and the text
 * weight gives it a reading that does not depend on seeing the fill at all.
 */
const tabsTrigger = cva(
  [
    'relative inline-flex items-center justify-center gap-1.5 whitespace-nowrap',
    'text-sm font-medium text-fg-muted',
    'transition-colors duration-90 ease-out',
    'hover:text-fg data-[state=active]:text-fg',
    'disabled:pointer-events-none disabled:opacity-50',
    "[&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-3.5",
  ],
  {
    variants: {
      variant: {
        solid: [
          'h-6 rounded-control border border-transparent px-2',
          'data-[state=active]:border-border data-[state=active]:bg-raised',
          'data-[state=active]:shadow-xs',
        ],
        line: 'border-transparent data-[state=active]:border-primary',
      },
      orientation: {
        horizontal: '',
        vertical: 'justify-start',
      },
    },
    compoundVariants: [
      { variant: 'line', orientation: 'horizontal', class: 'h-8 -mb-px border-b-2 px-0.5' },
      { variant: 'line', orientation: 'vertical', class: 'h-7 -ml-px border-l-2 px-2' },
      { variant: 'solid', orientation: 'vertical', class: 'w-full' },
    ],
    defaultVariants: { variant: 'solid', orientation: 'horizontal' },
  },
)

function TabsTrigger({ className, ...props }: React.ComponentProps<typeof TabsPrimitive.Trigger>) {
  const { variant, orientation } = React.useContext(TabsStyleContext)

  return (
    <TabsPrimitive.Trigger
      data-slot="tabs-trigger"
      className={cn(tabsTrigger({ variant, orientation }), className)}
      {...props}
    />
  )
}

function TabsContent({ className, ...props }: React.ComponentProps<typeof TabsPrimitive.Content>) {
  return (
    <TabsPrimitive.Content
      data-slot="tabs-content"
      className={cn('flex-1', className)}
      {...props}
    />
  )
}

export { Tabs, TabsContent, TabsList, tabsList, TabsTrigger, tabsTrigger }
export type { TabsOrientation, TabsVariant }
export type TabsListVariants = VariantProps<typeof tabsList>
