import { Tooltip as TooltipPrimitive } from 'radix-ui'
import type * as React from 'react'
import { cn } from '@/lib/cn'

/**
 * Generated by `shadcn add tooltip`, then retuned. README.md has the mapping.
 *
 * **A tooltip is never a label.** It does not exist on touch, it does not exist
 * for a keyboard user who tabs past quickly, and Radix renders it as
 * `role="tooltip"` referenced by `aria-describedby` — a *description*, not a
 * name. So an icon-only button carries its own `aria-label` and the tooltip
 * repeats it for sighted mouse users. If the tooltip is the only place a control's
 * purpose is written down, the control is unlabelled.
 *
 * `bg-contrast text-contrast-fg` — the inverted surface, **17.76:1** light and
 * **16.10:1** dark. Inverting is what stops a tooltip from being mistaken for a
 * popover: same shape, opposite polarity, so it reads as an annotation over the
 * UI rather than a panel within it.
 *
 * `z-60` rather than the generated `z-50`. A tooltip on a control *inside* a
 * dialog has to clear the dialog, and the dialog is 50. The full ladder is in
 * README §3.
 *
 * `max-w-56` (224px) so a sentence wraps into a block instead of a 900px ribbon,
 * with `text-balance` to even the line lengths. Radix also exposes
 * `--radix-tooltip-content-available-width`, but a fixed maximum is the more
 * predictable of the two: a tooltip that is 224px wide everywhere is easier to
 * read than one whose shape depends on where its trigger happens to sit.
 */
function TooltipProvider({
  delayDuration = 400,
  ...props
}: React.ComponentProps<typeof TooltipPrimitive.Provider>) {
  return (
    <TooltipPrimitive.Provider
      data-slot="tooltip-provider"
      delayDuration={delayDuration}
      {...props}
    />
  )
}

function Tooltip({ ...props }: React.ComponentProps<typeof TooltipPrimitive.Root>) {
  return <TooltipPrimitive.Root data-slot="tooltip" {...props} />
}

function TooltipTrigger({ ...props }: React.ComponentProps<typeof TooltipPrimitive.Trigger>) {
  return <TooltipPrimitive.Trigger data-slot="tooltip-trigger" {...props} />
}

/**
 * `sideOffset = 6` leaves room for the arrow, which Radix draws *outside* the
 * content box: 5px of arrow plus 1px of air. The generated value was 0, which
 * put the arrow on top of the trigger.
 *
 * The arrow is Radix's own triangle with `fill-contrast`, replacing shadcn's
 * rotated-square trick (`size-2.5 rotate-45 rounded-[2px] bg-foreground
 * fill-foreground` plus a `translate-y-[calc(-50%_-_2px)]` correction). That hack
 * produces a slightly rounder tip and costs an arbitrary radius the lint rule
 * rejects, a magic translate, and a shape that has to be re-derived by hand every
 * time the offset changes. Keeping the arrow at all is deliberate: in a toolbar of
 * eight 24px icon buttons, the arrow is what says *which one*.
 */
function TooltipContent({
  className,
  sideOffset = 6,
  children,
  ...props
}: React.ComponentProps<typeof TooltipPrimitive.Content>) {
  return (
    <TooltipPrimitive.Portal>
      <TooltipPrimitive.Content
        data-slot="tooltip-content"
        sideOffset={sideOffset}
        className={cn(
          'z-60 w-fit max-w-56 origin-(--radix-tooltip-content-transform-origin)',
          'rounded-control bg-contrast px-2 py-1',
          'text-xs text-balance text-contrast-fg',
          'data-[state=open]:animate-pop-in data-[state=closed]:animate-pop-out',
          'data-[side=bottom]:pop-from-top data-[side=top]:pop-from-bottom',
          'data-[side=left]:pop-from-right data-[side=right]:pop-from-left',
          className,
        )}
        {...props}
      >
        {children}
        <TooltipPrimitive.Arrow width={10} height={5} className="fill-contrast" />
      </TooltipPrimitive.Content>
    </TooltipPrimitive.Portal>
  )
}

export { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger }
