import { setupWorker } from 'msw/browser'
import { handlers } from './handlers'

/**
 * ══════════════════════════════════════════════════════════════════════
 * The MSW service worker — the API, in a real browser, before the API exists.
 * ══════════════════════════════════════════════════════════════════════
 *
 * `msw/browser`, where ./server.ts is `msw/node`. The two are not
 * interchangeable and neither replaces the other: Vitest runs under jsdom, which has no
 * service worker at all, and `pnpm dev` runs in Chrome, where a service worker is the
 * only way to intercept a request the app makes through the real `fetch`. Same
 * `handlers`, so the browser and the test suite cannot disagree about what the API
 * returns — which is the entire reason the handler list is a separate module.
 *
 * `public/mockServiceWorker.js` is the worker script itself, generated by `msw init` and
 * committed. The `msw.workerDirectory` field in `package.json` is what lets MSW check it
 * is current and warn if the installed version has moved past it.
 *
 * ### Why this file lives in `src/test/`
 *
 * Because `handlers.ts` does, and duplicating a handler list to avoid an awkward
 * directory name is how the mock the browser sees drifts from the mock the tests see.
 * `vite.config.ts` already names this path in its proxy comment.
 *
 * The consequence to be aware of: `tsconfig.json` excludes `src/test/**` from its *root*
 * file set, but a file reached by an import is still added to the program — so this
 * module and `handlers.ts` are typechecked by the application project, with
 * `types: ["vite/client"]` and no node types. That is stricter than the test project,
 * not looser: a `node:` import that strayed in here would fail `pnpm typecheck`.
 *
 * ### This module is never in the production bundle
 *
 * `main.tsx` reaches this through a **dynamic** `import()` inside a condition that
 * constant-folds to `false` in a production build (`import.meta.env.DEV` is replaced with
 * a literal), so Rollup drops the branch and the chunk with it. A static import would
 * ship MSW, `@flux/mocks` and every fixture to real users — roughly the size of the
 * application itself, and a set of handlers sitting next to the real API waiting to be
 * enabled by an environment variable. Measured: the production bundle contains zero
 * occurrences of `msw`, `setupWorker`, `onUnhandledRequest` or `@flux/mocks`.
 *
 * ### The worker script was, and that is a different question
 *
 * The heading above used to read "It is never in the production bundle", and the word
 * doing the damage was *it*. Everything in this section is about the **module**, and all
 * of it is true. `public/mockServiceWorker.js` is not a module: it is a static asset with
 * no importer, tree-shaking is a property of imports, and so none of the reasoning here
 * ever applied to it. Vite copied it verbatim and `dist/mockServiceWorker.js` shipped in
 * every production build — a service worker on the application's own origin, which any
 * script on the page can register, and which then answers every request the page makes
 * from a list of fabricated fixtures until something unregisters it. CodeQL's first run
 * against this repository found the file and flagged its `message` handler
 * (`js/missing-origin-check`); the handler was the smaller half.
 *
 * `vite.config.ts` now sets `copyPublicDir: false`, and
 * `scripts/check-public-assets.mjs` fails if a dev-only asset appears in a build or if
 * anything unrecognised appears in `public/` — because `copyPublicDir: false` would
 * otherwise drop a legitimate future asset just as silently. The lesson worth keeping is
 * narrower than "check the bundle": a verified claim about one representation of a thing
 * is not a claim about the others, and confident prose is where that gap hides.
 */
export const worker = setupWorker(...handlers)

/**
 * Start intercepting, and resolve when the worker is actually in control.
 *
 * The await matters. `worker.start()` returns before the service worker has claimed the
 * page unless it is awaited, and the requests the app fires on its first render — the
 * bootstrap query, immediately — would go to the network and 404. The symptom is a shell
 * that shows its error state on a cold load and works after a refresh, which is a
 * miserable thing to debug.
 *
 * `onUnhandledRequest: 'warn'` rather than `'error'`: Vite's dev server serves the
 * module graph, `/@vite/client`, the HMR socket and every source file through the same
 * origin, and failing on those would make the app unrunnable. A warn still puts an
 * un-mocked `/api/v1/...` call in the console, which is the case worth hearing about.
 *
 * `quiet: false` so the "[MSW] Mocking enabled" line is printed — the app is showing
 * fabricated data, and that should never be a silent condition.
 */
export async function startMockWorker(): Promise<void> {
  await worker.start({
    onUnhandledRequest: 'warn',
    quiet: false,
    serviceWorker: { url: '/mockServiceWorker.js' },
  })
}
